### ISSUE TITLE
Lost library (Getting cleared)

### ISSUE THREAD

**Issue by joaoandre120** [tachiyomiorg/tachiyomi#10158]
### Steps to reproduce

Opening the app, the library was clean.
It's the 3ª time this happened, and I only remembered to save the crash report this time.

### Expected behavior

The library shouldn't be clean.

### Actual behavior

The library is cleared, and the only solution is to restore the backup.

### Crash logs

[tachiyomi_crash_logs - db clean.txt](https://github.com/tachiyomiorg/tachiyomi/files/13405013/tachiyomi_crash_logs.-.db.clean.txt)

### Tachiyomi version

0.14.7

### Android version

Android version: 10 (SDK 29)

### Device

UMIDIGI A9 Pro

### Other details

App version: 0.14.7 (standard, c8d6859, 102, 2023-10-25T16:11Z)
Android version: 10 (SDK 29)
Android build ID: UMIDIGI_A9_Pro_128GB.E_V1.0_20201109
Device brand: UMIDIGI
Device manufacturer: HXY
Device name: A9_Pro_128GB
Device model: A9 Pro
Device product name: A9_Pro_EEA

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by joaoandre120** [comment]
Just happened again.
[tachiyomi_crash_logs - db clean 2.txt](https://github.com/tachiyomiorg/tachiyomi/files/13405141/tachiyomi_crash_logs.-.db.clean.2.txt)

**Comment by arkon** [comment]
```
11-19 21:37:24.572  3051  1507 E SQLiteLog: (11) database corruption at line 68757 of [698edb7753]
11-19 21:37:24.572  3051  1507 E SQLiteLog: (11) database corruption at line 68907 of [698edb7753]
11-19 21:37:24.572  3051  1507 E SQLiteLog: (11) statement aborts at 36: [SELECT *
11-19 21:37:24.572  3051  1507 E SQLiteLog: FROM updatesView
11-19 21:37:24.572  3051  1507 E SQLiteLog: WHERE dateUpload > ?] database disk image is malformed
11-19 21:37:24.574  3051  1507 E SupportSQLite: Corruption reported by sqlite on database: SQLiteDatabase: /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db.path
11-19 21:37:25.015  3051 26069 E SQLiteLog: (11) database corruption at line 68757 of [698edb7753]
11-19 21:37:25.015  3051 26069 E SQLiteLog: (11) database corruption at line 68907 of [698edb7753]
11-19 21:37:25.015  3051 26069 E SQLiteLog: (11) statement aborts at 36: [SELECT *
11-19 21:37:25.015  3051 26069 E SQLiteLog: FROM updatesView
11-19 21:37:25.015  3051 26069 E SQLiteLog: WHERE dateUpload > ?] database disk image is malformed
11-19 21:37:25.016  3051 26069 E SupportSQLite: Corruption reported by sqlite on database: SQLiteDatabase: /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db.path
11-19 21:37:25.796  3051 26067 E SQLiteLog: (11) database corruption at line 68757 of [698edb7753]
11-19 21:37:25.796  3051 26067 E SQLiteLog: (11) database corruption at line 68907 of [698edb7753]
11-19 21:37:25.796  3051 26067 E SQLiteLog: (11) statement aborts at 48: [SELECT *
11-19 21:37:25.796  3051 26067 E SQLiteLog: FROM libraryView] database disk image is malformed
11-19 21:37:25.797  3051 26067 E SupportSQLite: Corruption reported by sqlite on database: SQLiteDatabase: /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db.path
11-19 21:37:26.068  3051  1163 E SQLiteLog: (11) database corruption at line 68757 of [698edb7753]
11-19 21:37:26.069  3051  1163 E SQLiteLog: (11) database corruption at line 68907 of [698edb7753]
11-19 21:37:26.069  3051  1163 E SQLiteLog: (11) statement aborts at 30: [SELECT
11-19 21:37:26.069  3051  1163 E SQLiteLog: id,
11-19 21:37:26.069  3051  1163 E SQLiteLog: mangaId,
11-19 21:37:26.069  3051  1163 E SQLiteLog: chapterId,
11-19 21:37:26.069  3051  1163 E SQLiteLog: title,
11-19 21:37:26.069  3051  1163 E SQLiteLog: thumbnailUrl,
11-19 21:37:26.069  3051  1163 E SQLiteLog: source,
11-19 21:37:26.069  3051  1163 E SQLiteLog: favorite,
11-19 21:37:26.069  3051  1163 E SQLiteLog: cover_last_modified,
11-19 21:37:26.069  3051  1163 E SQLiteLog: chapterNumber,
11-19 21:37:26.069  3051  1163 E SQLiteLog: readAt,
11-19 21:37:26.069  3051  1163 E SQLiteLog: readDuration
11-19 21:37:26.069  3051  1163 E SQLiteLog: FROM historyView
11-19 21:37:26.069  3051  1163 E SQLiteLog: WHERE historyView.readAt > 0
11-19 21:37:26.069  3051  1163 E SQLiteLog: AND maxRead
11-19 21:37:26.069  3051  1163 E SupportSQLite: Corruption reported by sqlite on database: SQLiteDatabase: /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db.path
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: android.database.sqlite.SQLiteDatabaseCorruptException: database disk image is malformed (code 11)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at io.requery.android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:90)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at io.requery.android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:37)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at io.requery.android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:31)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at io.requery.android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:31)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at io.requery.android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:7)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at io.requery.android.database.AbstractCursor.moveToPosition(AbstractCursor.java:1)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at io.requery.android.database.AbstractCursor.moveToNext(AbstractCursor.java:5)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at com.squareup.sqldelight.android.AndroidCursor.next(AndroidSqliteDriver.kt:3)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:10)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invoke(FlowExtensions.kt:13)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$$inlined$map$1$2.emit(Collect.kt:76)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:2)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:18)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$asFlow$1.invokeSuspend(FlowExtensions.kt:120)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
11-19 21:37:26.074  3051  1163 E HistoryScreenModel: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: android.database.sqlite.SQLiteDatabaseCorruptException: database disk image is malformed (code 11)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at io.requery.android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:90)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at io.requery.android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:37)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at io.requery.android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:31)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at io.requery.android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:31)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at io.requery.android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:7)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at io.requery.android.database.AbstractCursor.moveToPosition(AbstractCursor.java:1)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at io.requery.android.database.AbstractCursor.moveToNext(AbstractCursor.java:5)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at com.squareup.sqldelight.android.AndroidCursor.next(AndroidSqliteDriver.kt:3)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:10)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invoke(FlowExtensions.kt:13)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$$inlined$map$1$2.emit(Collect.kt:76)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:2)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:18)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$asFlow$1.invokeSuspend(FlowExtensions.kt:120)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
11-19 21:37:26.075  3051 26069 E ChannelFlowTransformLatest: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
11-19 21:37:26.076  3051 26067 E SQLiteLog: (28) file unlinked while open: /data/data/eu.kanade.tachiyomi/databases/tachiyomi.db
```

It's crashing because your database is somehow corrupt and it's also full of garbage in the crash dump.

I wouldn't be really surprised if this is just the cheap Chinese phone dying?

**Comment by joaoandre120** [comment]
> I wouldn't be really surprised if this is just the cheap Chinese phone dying?
I hope not, and I don't have problems with other apps.
