### ISSUE TITLE
Crash on extension download (MIUI Android 13)

### ISSUE THREAD

**Issue by DarkVen0m** [tachiyomiorg/tachiyomi#10155]
### Steps to reproduce

1. Open app
2. Go to browser -> extensions
3. Try to install any extension

### Expected behavior

Extension is installed

### Actual behavior

App crash, log attached

### Crash logs

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getLastPathSegment()' on a null object reference
 at android.app.DownloadManager.enqueue(Unknown Source:14)
 at eu.kanade.tachiyomi.extension.util.ExtensionInstaller.downloadAndInstall(SourceFile:93)
 at eu.kanade.tachiyomi.extension.ExtensionManager.installExtension(Unknown Source:10)
 at eu.kanade.tachiyomi.ui.extension.ExtensionBottomPresenter$installExtension$1.invokeSuspend(Unknown Source:52)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
 at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
 Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3aace6a, Dispatchers.Default]

### Tachiyomi version

0.14.7

### Android version

Android 13

### Device

Poco F5

### Other details

I know MIUI is being MIUI, but I didn't found any issue regarding downloading, not actually installing extensions
As well I've tried to debug it by myself, but as you can guess - no luck
downloadUri passed to DownloadManager.Request is definitely not null
![image](https://github.com/tachiyomiorg/tachiyomi/assets/16627883/42998ffc-43d4-4431-9681-df07c5e3f36b)

So that's probably something about context inside of DownloadManager
![image](https://github.com/tachiyomiorg/tachiyomi/assets/16627883/c21fc19d-c44a-47b2-b692-39a374670f68)
![image](https://github.com/tachiyomiorg/tachiyomi/assets/16627883/947515a6-d27e-4b3c-bb07-5cd1ac9ba657)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by DarkVen0m** [comment]
Clearing download manager data fixed it
Writing it here in case someone else will run into same issue
