### ISSUE TITLE
App crashes when loading private non-read-only extension

### ISSUE THREAD

**Issue by Soitora** [tachiyomiorg/tachiyomi#10252]
### Steps to reproduce

1. Be on `Preview`
2. Use `Private` installation method
3. Use a series that apparently "is not allowed" according to logs (in this case: `Asura Scans`)

### Expected behavior

Extension should be disabled, or uninstalled, and the app should function

### Actual behavior

Infinite bootloop, can't uninstall extension as normal either due to it being Private

### Crash logs

```bash
FATAL EXCEPTION: main
Process: eu.kanade.tachiyomi.debug:error_handler, PID: 24024
java.lang.SecurityException: Writable dex file '/data/user/0/eu.kanade.tachiyomi.debug/files/exts/eu.kanade.tachiyomi.extension.all.asurascans.ext' is not allowed.
    at dalvik.system.DexFile.openDexFileNative(Native Method)
    at dalvik.system.DexFile.openDexFile(DexFile.java:406)
    at dalvik.system.DexFile.<init>(DexFile.java:128)
    at dalvik.system.DexFile.<init>(DexFile.java:101)
    at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
    at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
    at dalvik.system.DexPathList.<init>(DexPathList.java:166)
    at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
    at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:105)
    at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:71)
    at eu.kanade.tachiyomi.extension.util.ExtensionLoader.loadExtension(SourceFile:244)
    at eu.kanade.tachiyomi.extension.util.ExtensionLoader$loadExtensions$1$deferred$1$1.invokeSuspend(SourceFile:12)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
    at kotlinx.coroutines.DispatchedTask.run(SourceFile:111)
    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:153)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(SourceFile:29)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(SourceFile:77)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(SourceFile:7)
    at kotlinx.coroutines.BuildersKt.runBlocking$default(SourceFile:1)
    at eu.kanade.tachiyomi.extension.util.ExtensionLoader.loadExtensions(SourceFile:155)
    at eu.kanade.tachiyomi.extension.ExtensionManager.<init>(SourceFile:119)
    at eu.kanade.tachiyomi.di.AppModule$registerInjectables$11.invoke(SourceFile:7)
    at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1$$special$$inlined$getOrPut$lambda$1.invoke(SourceFile:5)
    at kotlin.SynchronizedLazyImpl.getValue(SourceFile:21)
    at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1.invoke(SourceFile:45)
    at uy.kohesive.injekt.registry.default.DefaultRegistrar.getInstance(SourceFile:16)
    at eu.kanade.tachiyomi.di.AppModule$registerInjectables$10.invoke(SourceFile:18)
    at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1$$special$$inlined$getOrPut$lambda$1.invoke(SourceFile:5)
    at kotlin.SynchronizedLazyImpl.getValue(SourceFile:21)
    at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1.invoke(SourceFile:45)
    at uy.kohesive.injekt.registry.default.DefaultRegistrar.getInstance(SourceFile:16)
    at androidx.work.CoroutineWorker$$ExternalSyntheticLambda0.run(SourceFile:43)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8194)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

### Tachiyomi version

r6309

### Android version

Android 14

### Device

Google Pixel 8 Pro

### Other details

The extension that is now "not allowed" has not been marked as such in the app prior to this, I don't keep Obsolete extensions

This does not belong to the Extensions repo because it's a main app crash that the user is not told about
I had to use ADB and Logcat to find out the error

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Related: #10007

This only affects previously installed private extensions for Android 14+ users after we started targeting SDK 34 (13b3bec8ad2a5b883cbe5ec99da531fbaba7f50b).
