### ISSUE TITLE
[Bug] Opening a local source crashes the app

### ISSUE THREAD

**Issue by whowatchlist** [tachiyomiorg/tachiyomi#4156]
## Device information
* Tachiyomi version: 0.10.7
* Android version: 8.0.0
* Device: lg v30

## Steps to reproduce
1. Place folder with acceptably structured manga in /tachiyomi/local
2. Access said manga in app from local sources

### Expected behavior
Open the manga 

### Actual behavior
The app crashes

## Other details
I'm not sure but I think the relevant log is this:

Error inserting _data=/storage/emulated/0/Tachiyomi/local storage_type=65537 parent=74706 _display_name=local burst_id=null format=12289 title=local is_hifi=0 bucket_id=1348034351 _size=4096 date_added=1608403638 date_modified=1608395904 media_type=0 storage_id=65537 is_lock=0 bucket_display_name=Tachiyomi
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: files._data (code 2067)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:788)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:926)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1584)
	at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1453)
	at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:3164)
	at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:3595)
	at com.android.providers.media.MediaProvider.insert(MediaProvider.java:2585)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:268)
	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:152)
	at android.os.Binder.execTransact(Binder.java:690)

This log is from before the crash, so if you want a log from during the crash I can get that.

This issue does not happen on the latest dev, and this specific log does not show up, so this may be fixed idk

**Comment by arkon** [comment]
Have you tried clearing the database from the advanced settings?

**Comment by zetaisgood** [comment]
In my case the r3013 version crashes the same way. Curiously, I can open the manga after waiting some time (a day, maybe).

**Comment by Pandakuta** [comment]
same problem, tried different format but still crash/app close
