### ISSUE TITLE
[Bug] Global Search not working

### ISSUE THREAD

**Issue by REDSenpai002** [tachiyomiorg/tachiyomi#4182]
---

## Device information
* Tachiyomi version: 0.10.7
* Android version: 9
* Device: Samsung SM-J330F

## Steps to reproduce
1. Open Tachiyomi
2. Go to browse
3. Enter Global search
4. Search anything

### Expected behavior
Complete the search

### Actual behavior
Right before finishing the search the app crashes

## Other details
[logcat_12-23-2020_21-28-59.txt](https://github.com/tachiyomiorg/tachiyomi/files/5736851/logcat_12-23-2020_21-28-59.txt)

**Comment by arkon** [comment]
The attached log file only has some things from the logcat app itself. Did you grant it permissions to view other logs?

**Comment by REDSenpai002** [comment]
I hope this one works
[bugreport-2020-12-24-01-38-36.zip](https://github.com/tachiyomiorg/tachiyomi/files/5737491/bugreport-2020-12-24-01-38-36.zip)

**Comment by arkon** [comment]
```
12-24 01:33:13.043 11258 18393 18468 E ACRA    : ACRA caught a IllegalStateException for eu.kanade.tachiyomi
12-24 01:33:13.043 11258 18393 18468 E ACRA    : java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at java.lang.Thread.run(Thread.java:764)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : Caused by: java.lang.NoSuchMethodError: No virtual method load(Lkotlinx/serialization/DeserializationStrategy;[B)Ljava/lang/Object; in class Lkotlinx/serialization/protobuf/ProtoBuf$Default; or its super classes (declaration of 'kotlinx.serialization.protobuf.ProtoBuf$Default' appears in base.apk!classes2.dex)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at eu.kanade.tachiyomi.extension.all.mangaplus.MangaPlus.asProto(MangaPlus.kt:404)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at eu.kanade.tachiyomi.extension.all.mangaplus.MangaPlus.searchMangaParse(MangaPlus.kt:146)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at eu.kanade.tachiyomi.source.online.HttpSource$fetchSearchManga$1.call(HttpSource.kt:125)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at eu.kanade.tachiyomi.source.online.HttpSource$fetchSearchManga$1.call(HttpSource.kt:26)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:30)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber$1.request(OperatorSubscribeOn.java:109)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.setProducer(OperatorOnErrorResumeNextViaFunction.java:159)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.setProducer(OperatorSubscribeOn.java:105)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.Subscriber.setProducer(Subscriber.java:205)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.Subscriber.setProducer(Subscriber.java:205)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:50)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:18)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
12-24 01:33:13.043 11258 18393 18468 E ACRA    : 	... 6 more
```

**Comment by arkon** [comment]
Have you updated your MangaPlus extension? You can try reinstalling it too.
