### ISSUE TITLE
[Bug] Cover from guya.moe extension can't be decoded

### ISSUE THREAD

**Issue by scb261** [tachiyomiorg/tachiyomi#4713]
## Device information
* Tachiyomi version: 0.10.9 and r3172
* Android version: 5.1 / 11
* Device: Huawei TIT-U02 / Pixel 4a

## Steps to reproduce
1. Open guya.moe source and scroll down

### Expected behavior
All covers load.

### Actual behavior
Some covers don't load until clearing database several times, but even then cover for "We Want To Talk About Kaguya" doesn't load.

## Other details
It loaded just fine on emulator, but someone else on discord has the same problem with Pixel 4a and preview tachi.
<details>
<summary>They even cleared library and added only this one manga to library to check the cover file</summary>

![image](https://user-images.githubusercontent.com/65343233/112465148-0af96400-8d6d-11eb-9a0e-bf140458f4e4.png)
![image](https://user-images.githubusercontent.com/65343233/112465165-0f258180-8d6d-11eb-80bb-cfeb0ba1b678.png)
![image](https://user-images.githubusercontent.com/65343233/112466197-3fb9eb00-8d6e-11eb-93e3-0b668ca03e9b.png)

</details>

While I typed this issue, the cover finally was shown in r3172 on my phone, but I got logcat for the error while it was present:

<details>
<summary>Logcat</summary>

```
03-25 13:03:13.734 21746-21843/eu.kanade.tachiyomi.debug W/System.err: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
03-25 13:03:13.741 21746-21836/eu.kanade.tachiyomi.debug W/System.err: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
03-25 13:03:13.744 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:355)
03-25 13:03:13.744 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281)
03-25 13:03:13.744 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
03-25 13:03:13.744 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at java.io.FilterInputStream.read(FilterInputStream.java:118)
03-25 13:03:13.744 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:71)
03-25 13:03:13.744 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:66)
03-25 13:03:13.744 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:137)
03-25 13:03:13.744 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:305)
03-25 13:03:13.744 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.util.ExceptionPassthroughInputStream.read(ExceptionPassthroughInputStream.java:105)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at java.io.FilterInputStream.read(FilterInputStream.java:118)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.util.MarkEnforcingInputStream.read(MarkEnforcingInputStream.java:46)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at java.io.InputStream.read(InputStream.java:162)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:137)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:305)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:712)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:688)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.ImageReader$InputStreamImageReader.decodeBitmap(ImageReader.java:50)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:742)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:390)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:248)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:207)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:62)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:18)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:92)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:529)
03-25 13:03:13.745 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:493)
03-25 13:03:13.746 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:479)
03-25 13:03:13.746 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:430)
03-25 13:03:13.746 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:283)
03-25 13:03:13.746 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
03-25 13:03:13.746 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-25 13:03:13.746 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-25 13:03:13.746 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at java.lang.Thread.run(Thread.java:818)
03-25 13:03:13.746 21746-21836/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
03-25 13:03:13.746 21746-21836/eu.kanade.tachiyomi.debug D/skia: ---- read threw an exception
03-25 13:03:13.746 21746-21836/eu.kanade.tachiyomi.debug D/skia_png: png_error,msg:Read Error!
03-25 13:03:13.746 21746-21836/eu.kanade.tachiyomi.debug D/skia: --- decoder->decode returned false
03-25 13:03:13.748 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:355)
03-25 13:03:13.748 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281)
03-25 13:03:13.748 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
03-25 13:03:13.748 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at java.io.FilterInputStream.read(FilterInputStream.java:118)
03-25 13:03:13.748 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:71)
03-25 13:03:13.748 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:66)
03-25 13:03:13.748 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:137)
03-25 13:03:13.748 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:305)
03-25 13:03:13.748 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.util.ExceptionPassthroughInputStream.read(ExceptionPassthroughInputStream.java:105)
03-25 13:03:13.748 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at java.io.FilterInputStream.read(FilterInputStream.java:118)
03-25 13:03:13.748 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.util.MarkEnforcingInputStream.read(MarkEnforcingInputStream.java:46)
03-25 13:03:13.748 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at java.io.InputStream.read(InputStream.java:162)
03-25 13:03:13.748 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(RecyclableBufferedInputStream.java:137)
03-25 13:03:13.748 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(RecyclableBufferedInputStream.java:305)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:712)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:688)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.ImageReader$InputStreamImageReader.decodeBitmap(ImageReader.java:50)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:742)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:390)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:248)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:207)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:62)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:18)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:92)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:529)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:493)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:479)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:430)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:283)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
03-25 13:03:13.749 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-25 13:03:13.750 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-25 13:03:13.750 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at java.lang.Thread.run(Thread.java:818)
03-25 13:03:13.750 21746-21843/eu.kanade.tachiyomi.debug W/System.err:     at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
03-25 13:03:13.750 21746-21843/eu.kanade.tachiyomi.debug D/skia: ---- read threw an exception
03-25 13:03:13.750 21746-21843/eu.kanade.tachiyomi.debug D/skia_png: png_error,msg:Read Error!
03-25 13:03:13.751 21746-21843/eu.kanade.tachiyomi.debug D/skia: --- decoder->decode returned false
```

</details>

**Comment by arkon** [comment]
Closing in favour of #4193
