### ISSUE TITLE
[Bug] Changing read type Crashes App

### ISSUE THREAD

**Issue by AngeredSpace** [tachiyomiorg/tachiyomi#4728]
## Device information
* Tachiyomi version: r3185 
* Android version: 11
* Device: Galaxy Tab 6

## Steps to reproduce
1. Open a manga in the reader and open the settings.
2. Change read type to weebtoon.

### Expected behavior
Should change read type.

### Actual behavior 
Crashes the app.

## Other details
Everytime Settings are opened in reader mode for the same manga the app will crash.

Crash logs
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6217063/tachiyomi_crash_logs.txt)

**Comment by arkon** [comment]
```
03-28 01:36:29.249  7060  7060 E ACRA    : ACRA caught a IndexOutOfBoundsException for eu.kanade.tachiyomi.debug
03-28 01:36:29.249  7060  7060 E ACRA    : java.lang.IndexOutOfBoundsException: Index: 25, Size: 5
03-28 01:36:29.249  7060  7060 E ACRA    : 	at java.util.ArrayList.get(ArrayList.java:437)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at androidx.appcompat.view.menu.MenuBuilder.getItem(MenuBuilder.java:752)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.setting.SpinnerPreference.popup(SpinnerPreference.kt:205)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.setting.SpinnerPreference.makeSettingsPopup(SpinnerPreference.kt:117)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.setting.SpinnerPreference.bindToIntPreference(SpinnerPreference.kt:90)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.setting.SpinnerPreference.bindToIntPreference$default(SpinnerPreference.kt:85)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderReadingModeSettings.initWebtoonPreferences(ReaderReadingModeSettings.kt:96)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderReadingModeSettings.<init>(ReaderReadingModeSettings.kt:38)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderReadingModeSettings.<init>(ReaderReadingModeSettings.kt:24)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.setting.ReaderSettingsSheet.<init>(ReaderSettingsSheet.kt:13)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$initializeMenu$$inlined$with$lambda$3.onClick(ReaderActivity.kt:382)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at android.view.View.performClick(View.java:8160)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at android.view.View.performClickInternal(View.java:8137)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at android.view.View.access$3700(View.java:888)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at android.view.View$PerformClick.run(View.java:30236)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:938)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at android.os.Looper.loop(Looper.java:246)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8506)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
03-28 01:36:29.249  7060  7060 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
