### ISSUE TITLE
[Bug] Tachi Crashes on mangadex settings

### ISSUE THREAD

**Issue by SamSensei** [tachiyomiorg/tachiyomi#5025]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 7.0
* Device: Redmi Note 4X

## Steps to reproduce
1. Goto mangadex extension settings
2. Tap on settings icon for English and tachi crashes

### Expected behavior
English settings for mangadex extension
### Actual behavior
Instead of English setting it crashes

## Other details
Crash log is attached
![Screenshot_2021-05-06-07-15-07-059_eu kanade tachiyomi](https://user-images.githubusercontent.com/35701119/117230887-ac2f0c00-ae3b-11eb-82c0-39870b4a81c4.jpg)
[Crash Log](https://app.box.com/s/ukdddjnzv3mt3tihgclv961x3ya75o46)

**Comment by nosut** [comment]
Can confirm I am having the same issue.

Note I am using SY however.

**Comment by arkon** [comment]
```
05-06 07:00:43.599 14913 14913 E AndroidRuntime: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
05-06 07:00:43.599 14913 14913 E AndroidRuntime: 	at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:225)
05-06 07:00:43.599 14913 14913 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.preference.SharedPreferencesDataStore.getString(SharedPreferencesDataStore.kt:50)
05-06 07:00:43.599 14913 14913 E AndroidRuntime: 	at androidx.preference.Preference.getPersistedString(Preference.java:1683)
05-06 07:00:43.599 14913 14913 E AndroidRuntime: 	at androidx.preference.ListPreference.onSetInitialValue(ListPreference.java:255)
05-06 07:00:43.599 14913 14913 E AndroidRuntime: 	at androidx.preference.Preference.onSetInitialValue(Preference.java:1614)
```
