### ISSUE TITLE
[Bug] Crashing Problem in r3497

### ISSUE THREAD

**Issue by LenKiMo** [tachiyomiorg/tachiyomi#5364]
## Device information
* Tachiyomi version: 0.11.1-3497 (r3497)
* Android version: 10
* Device: Meizu 16s Pro

## Steps to reproduce
1. Start App

### Expected behavior
App starts normally.

### Actual behavior
App crashs.

## Other details

Logs Here:
https://anonbin.io/?173dc6a867df5f47#51bd499Sw43sd7KvZhpL1jcaiEuVfvyPqRkxgmiCGaGk

**Comment by arkon** [comment]
```
[06-10 09:25:28.553 22776:22842 E/ACRA]
ACRA caught a IllegalStateException for eu.kanade.tachiyomi.debug
java.lang.IllegalStateException: Not implemented
	at androidx.work.CoroutineWorker.getForegroundInfo$suspendImpl(CoroutineWorker.kt:101)
	at androidx.work.CoroutineWorker.getForegroundInfo(Unknown Source:0)
	at androidx.work.CoroutineWorker$getForegroundInfoAsync$1.invokeSuspend(CoroutineWorker.kt:136)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

Might be fixed by 07de367476cb337f597880b6f73e8c53e9b2fd19 in the next preview release. If not, we can rollback the version of WorkManager we're using.

**Comment by LenKiMo** [comment]
Crashing problem still in r3520.

Log:
https://anonbin.io/?fca76368ada8a37b#AQwEKkcJ5bReHkcM4BihG9NQaDVYzr7WHPsW6VfqoSz8

**Comment by arkon** [comment]
I've downgraded WorkManager, so you can try again with the next preview build.

**Comment by LenKiMo** [comment]
Solved in r3521.
