### ISSUE TITLE
Tachiyomi Force Close when Press Search On Setting

### ISSUE THREAD

**Issue by nurananto** [tachiyomiorg/tachiyomi#6122]
### Steps to reproduce

1. Open App
2. Open Setting
3. Click on Search button

### Expected behavior

start input search word

### Actual behavior

App Force Close

### Crash logs

ACRA caught a NullPointerException for eu.kanade.tachiyomi.debug
java.lang.NullPointerException
	at eu.kanade.tachiyomi.ui.setting.SettingsSecurityController.setupPreferenceScreen(SettingsSecurityController.kt:8)
	at eu.kanade.tachiyomi.ui.setting.search.SettingsSearchHelper$initPreferenceSearchResultCollection$1.invokeSuspend(SettingsSearchHelper.kt:5)
	at eu.kanade.tachiyomi.ui.setting.search.SettingsSearchHelper$initPreferenceSearchResultCollection$1.invoke(Unknown Source:8)
	at eu.kanade.tachiyomi.ui.setting.search.SettingsSearchHelper$initPreferenceSearchResultCollection$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:14)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:8)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:5)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at eu.kanade.tachiyomi.util.lang.CoroutinesExtensionsKt.launchNow(CoroutinesExtensions.kt:1)
	at eu.kanade.tachiyomi.ui.setting.search.SettingsSearchHelper.initPreferenceSearchResultCollection(SettingsSearchHelper.kt:3)
	at eu.kanade.tachiyomi.ui.setting.search.SettingsSearchController.onViewCreated(SettingsSearchController.kt:5)
	at eu.kanade.tachiyomi.ui.base.controller.BaseController$1.postCreateView(BaseController.kt:1)
	at com.bluelinelabs.conductor.Controller.inflate(Controller.java:12)
	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:17)
	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:22)
	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:29)
	at com.bluelinelabs.conductor.Router.pushController(Router.java:4)
	at eu.kanade.tachiyomi.ui.setting.SettingsMainController$onCreateOptionsMenu$1.onMenuItemActionExpand(SettingsMainController.kt:2)
	at androidx.appcompat.view.menu.MenuItemImpl.expandActionView(MenuItemImpl.java:3)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:15)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:2)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:2)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### Tachiyomi version

Preview R3903

### Android version

Android 11

### Device

Redmi Note 8 Ginkgo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by midyHamdoun** [comment]
I'll work on that if no one else is!

**Comment by arkon** [comment]
@midyHamdoun go ahead
