### ISSUE TITLE
App Update fails 

### ISSUE THREAD

**Issue by Seishirou101** [tachiyomiorg/tachiyomi#6277]
### Steps to reproduce

About -> check for updates -> wait for download to complete -> attempt to install through notification

*not always reproducible as of now, attempting these steps will work as expected...

### Expected behavior

installation is complete

### Actual behavior

app fails to install through package installer and when using sai, the error is "DISPLAY_NAME COLUMN is null" with the error being spit out of the logcat being something a long the lines of
```
java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri... 
```
If manually navigating to update.apk and opening, the error is 
```
java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{57004ef 28499:com.aefyr.sai/u0a153} (pid=28499, uid=10153) that is not exported from UID 10144
    at android.os.Parcel.createException(Parcel.java:1950)
    at android.os.Parcel.readException(Parcel.java:1918)
    at android.os.Parcel.readException(Parcel.java:1868)
    at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:4122)
    at android.app.ActivityThread.acquireProvider(ActivityThread.java:6173)
    at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2613)
    at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1902)
    at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1465)
    at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1318)
    at android.content.ContentResolver.openInputStream(ContentResolver.java:1022)
    at com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor.open(ContentUriFileDescriptor.java:47)
    at com.aefyr.sai.model.apksource.DefaultApkSource.openApkInputStream(DefaultApkSource.java:32)
    at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.install(RootlessSaiPackageInstaller.java:94)
    at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.lambda$enqueueSession$0$RootlessSaiPackageInstaller(RootlessSaiPackageInstaller.java:70)
    at com.aefyr.sai.installer2.impl.rootless.-$$Lambda$RootlessSaiPackageInstaller$ivyAcunEgIkYlu_dB2vN6MOWZPU.run(Unknown Source:6)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
```

### Tachiyomi version

Issue may happen on multiple versions.

### Android version

9

### Device

ASUS ROG Phone 2

### Other details

Similar issue #4572. For me during the period of testing, downloading from the website worked fine. but in 4572, downloading had to be done 3 times by me and ~11 times by op which failed until they downloaded and transferred the file.

there have been sparse reports of the issue happening with the advice usually given to ignore built in updater and attempting with various levels of success of:

1) a different browser
2) a different file manager
3) move the file somewhere else, ideally internal
4) use a different device and transfer it over

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
The fact that it doesn't work even when you try to open the APK manually indicates that it's a system issue rather than an app issue.

I have no idea why this sometimes happens though. You could try restarting your device the next time it happens?

**Comment by Seishirou101** [comment]
I don't either, I actually didn't restart when the issue was happening, but after attempting later, it worked as normal... glances at googling the logcat error leads to being with issues with intent permissions, but that doesn't explain why it works most times or downloading directly from github with a browser causes the issue... I've never seen the issue pop up for any other application when attempting to install/update like tachiyomi.

**Comment by NotTsunami** [comment]
Try uninstalling Split APK Installer.

**Comment by Seishirou101** [comment]
I'm not entirely sure if that would cause any issue, I only use sai to get a better error as the standard package installer gives you nothing other than "app not installed" or something a long those lines and the issue has happened to people without sai installed at all and we only find out the error by having them install sai
