### ISSUE TITLE
Crash on global search when obsolete extensions are installed

### ISSUE THREAD

**Issue by jogerj** [tachiyomiorg/tachiyomi#6603]
### Steps to reproduce

1. Install an obsolete extension (e.g. MangaRock)
2. Do global search
3. Crash

Or

1. Install an obsolete extension (e.g. MangaRock) 
2. Migrate any manga
3. Crash

### Expected behavior

Obsolete extensions should be ignored

### Actual behavior

Obsolete extensions are included in search which leads to crash

### Crash logs
<details><summary>Log 1</summary>

```
--------- beginning of main
02-08 12:02:19.618 21967 22050 E ACRA    : ACRA caught a IllegalStateException for eu.kanade.tachiyomi
02-08 12:02:19.618 21967 22050 E ACRA    : java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
02-08 12:02:19.618 21967 22050 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:3)
02-08 12:02:19.618 21967 22050 E ACRA    : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
02-08 12:02:19.618 21967 22050 E ACRA    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-08 12:02:19.618 21967 22050 E ACRA    : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
02-08 12:02:19.618 21967 22050 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-08 12:02:19.618 21967 22050 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-08 12:02:19.618 21967 22050 E ACRA    : 	at java.lang.Thread.run(Thread.java:920)
02-08 12:02:19.618 21967 22050 E ACRA    : Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/salomonbrys/kotson/BuilderKt;
02-08 12:02:19.618 21967 22050 E ACRA    : 	at eu.kanade.tachiyomi.extension.en.mangarock.MangaRock.searchMangaRequest(MangaRock.kt:113)
02-08 12:02:19.618 21967 22050 E ACRA    : 	at eu.kanade.tachiyomi.source.online.HttpSource.fetchSearchManga(HttpSource.kt:1)
02-08 12:02:19.618 21967 22050 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.globalsearch.GlobalSearchPresenter$$ExternalSyntheticLambda4.call(R8$$SyntheticClass:2)
02-08 12:02:19.618 21967 22050 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:2)
02-08 12:02:19.618 21967 22050 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:1)
02-08 12:02:19.618 21967 22050 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:2)
02-08 12:02:19.618 21967 22050 E ACRA    : 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:4)
02-08 12:02:19.618 21967 22050 E ACRA    : 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:2)
02-08 12:02:19.618 21967 22050 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:2)
02-08 12:02:19.618 21967 22050 E ACRA    : 	... 6 more
02-08 12:02:19.618 21967 22050 E ACRA    : Caused by: java.lang.ClassNotFoundException: com.github.salomonbrys.kotson.BuilderKt
02-08 12:02:19.618 21967 22050 E ACRA    : 	... 15 more
02-08 12:02:19.911  2894  2894 E .tachiyomi:acr: Not starting debugger since process cannot load the jdwp agent.
02-08 12:02:21.815  2965  2965 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-08 12:02:22.048  2965  3019 E SQLiteLog: (284) automatic index on C(manga_id)
02-08 12:02:22.048  2965  3019 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-08 12:02:30.762  2965  3138 E chromium: [ERROR:simple_index_file_posix.cc(36)] opendir /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
02-08 12:02:30.762  2965  3138 E chromium: [ERROR:simple_index_file.cc(575)] Could not reconstruct index from disk
02-08 12:02:32.360  2965  3116 E ACRA    : ACRA caught a IllegalStateException for eu.kanade.tachiyomi
02-08 12:02:32.360  2965  3116 E ACRA    : java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
02-08 12:02:32.360  2965  3116 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:3)
02-08 12:02:32.360  2965  3116 E ACRA    : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
02-08 12:02:32.360  2965  3116 E ACRA    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-08 12:02:32.360  2965  3116 E ACRA    : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
02-08 12:02:32.360  2965  3116 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-08 12:02:32.360  2965  3116 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-08 12:02:32.360  2965  3116 E ACRA    : 	at java.lang.Thread.run(Thread.java:920)
02-08 12:02:32.360  2965  3116 E ACRA    : Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/salomonbrys/kotson/BuilderKt;
02-08 12:02:32.360  2965  3116 E ACRA    : 	at eu.kanade.tachiyomi.extension.en.mangarock.MangaRock.searchMangaRequest(MangaRock.kt:113)
02-08 12:02:32.360  2965  3116 E ACRA    : 	at eu.kanade.tachiyomi.source.online.HttpSource.fetchSearchManga(HttpSource.kt:1)
02-08 12:02:32.360  2965  3116 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.globalsearch.GlobalSearchPresenter$$ExternalSyntheticLambda4.call(R8$$SyntheticClass:2)
02-08 12:02:32.360  2965  3116 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:2)
02-08 12:02:32.360  2965  3116 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:1)
02-08 12:02:32.360  2965  3116 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:2)
02-08 12:02:32.360  2965  3116 E ACRA    : 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:4)
02-08 12:02:32.360  2965  3116 E ACRA    : 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:2)
02-08 12:02:32.360  2965  3116 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:2)
02-08 12:02:32.360  2965  3116 E ACRA    : 	... 6 more
02-08 12:02:32.360  2965  3116 E ACRA    : Caused by: java.lang.ClassNotFoundException: com.github.salomonbrys.kotson.BuilderKt
02-08 12:02:32.360  2965  3116 E ACRA    : 	... 15 more
02-08 12:02:34.525  3230  3230 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-08 12:02:34.750  3230  3287 E SQLiteLog: (284) automatic index on C(manga_id)
02-08 12:02:34.750  3230  3287 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-08 12:02:59.937  3230  3516 E chromium: [ERROR:simple_backend_impl.cc(78)] Failed to create directory: /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js
02-08 12:03:01.430  3230  3493 E ACRA    : ACRA caught a IllegalStateException for eu.kanade.tachiyomi
02-08 12:03:01.430  3230  3493 E ACRA    : java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
02-08 12:03:01.430  3230  3493 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:3)
02-08 12:03:01.430  3230  3493 E ACRA    : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
02-08 12:03:01.430  3230  3493 E ACRA    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-08 12:03:01.430  3230  3493 E ACRA    : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
02-08 12:03:01.430  3230  3493 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-08 12:03:01.430  3230  3493 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-08 12:03:01.430  3230  3493 E ACRA    : 	at java.lang.Thread.run(Thread.java:920)
02-08 12:03:01.430  3230  3493 E ACRA    : Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/salomonbrys/kotson/BuilderKt;
02-08 12:03:01.430  3230  3493 E ACRA    : 	at eu.kanade.tachiyomi.extension.en.mangarock.MangaRock.searchMangaRequest(MangaRock.kt:113)
02-08 12:03:01.430  3230  3493 E ACRA    : 	at eu.kanade.tachiyomi.source.online.HttpSource.fetchSearchManga(HttpSource.kt:1)
02-08 12:03:01.430  3230  3493 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.globalsearch.GlobalSearchPresenter$$ExternalSyntheticLambda4.call(R8$$SyntheticClass:2)
02-08 12:03:01.430  3230  3493 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:2)
02-08 12:03:01.430  3230  3493 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:1)
02-08 12:03:01.430  3230  3493 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:2)
02-08 12:03:01.430  3230  3493 E ACRA    : 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:4)
02-08 12:03:01.430  3230  3493 E ACRA    : 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:2)
02-08 12:03:01.430  3230  3493 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:2)
02-08 12:03:01.430  3230  3493 E ACRA    : 	... 6 more
02-08 12:03:01.430  3230  3493 E ACRA    : Caused by: java.lang.ClassNotFoundException: com.github.salomonbrys.kotson.BuilderKt
02-08 12:03:01.430  3230  3493 E ACRA    : 	... 15 more
02-08 12:03:03.266  3581  3581 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-08 12:03:03.493  3581  3632 E SQLiteLog: (284) automatic index on C(manga_id)
02-08 12:03:03.493  3581  3632 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.1 (standard, d6386cef4, 74, 2022-02-03T14:45Z)
Android version: 12 (SDK 31)
Android build ID: SQ1D.220105.007
Device brand: google
Device manufacturer: Google
Device name: oriole
Device model: Pixel 6
Device product name: oriole
```
</details>
<details><summary>Log 2</summary>

```
--------- beginning of main
02-08 12:06:56.988  3581  3581 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-08 12:06:56.988  3581  3581 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-08 12:06:56.991  3581  3581 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-08 12:06:56.991  3581  3581 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-08 12:07:01.045  3581  3581 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-08 12:07:01.045  3581  3581 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-08 12:07:01.046  3581  3581 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-08 12:07:01.046  3581  3581 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-08 12:07:05.638  3581  5018 E chromium: [ERROR:simple_index_file_posix.cc(48)] readdir /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/wasm: No such file or directory (2)
02-08 12:07:05.638  3581  5018 E chromium: [ERROR:simple_index_file.cc(575)] Could not reconstruct index from disk
--------- beginning of crash
02-08 12:07:08.104  3581  4963 E AndroidRuntime: FATAL EXCEPTION: RxIoScheduler-15
02-08 12:07:08.104  3581  4963 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 3581
02-08 12:07:08.104  3581  4963 E AndroidRuntime: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
02-08 12:07:08.104  3581  4963 E AndroidRuntime: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:3)
02-08 12:07:08.104  3581  4963 E AndroidRuntime: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
02-08 12:07:08.104  3581  4963 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-08 12:07:08.104  3581  4963 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
02-08 12:07:08.104  3581  4963 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-08 12:07:08.104  3581  4963 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-08 12:07:08.104  3581  4963 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
02-08 12:07:08.104  3581  4963 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/salomonbrys/kotson/BuilderKt;
02-08 12:07:08.104  3581  4963 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.en.mangarock.MangaRock.searchMangaRequest(MangaRock.kt:113)
02-08 12:07:08.104  3581  4963 E AndroidRuntime: 	at eu.kanade.tachiyomi.source.online.HttpSource.fetchSearchManga(HttpSource.kt:1)
02-08 12:07:08.104  3581  4963 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.source.globalsearch.GlobalSearchPresenter$$ExternalSyntheticLambda4.call(R8$$SyntheticClass:2)
02-08 12:07:08.104  3581  4963 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:2)
02-08 12:07:08.104  3581  4963 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:1)
02-08 12:07:08.104  3581  4963 E AndroidRuntime: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
02-08 12:07:08.104  3581  4963 E AndroidRuntime: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:4)
02-08 12:07:08.104  3581  4963 E AndroidRuntime: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:2)
02-08 12:07:08.104  3581  4963 E AndroidRuntime: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:2)
02-08 12:07:08.104  3581  4963 E AndroidRuntime: 	... 6 more
02-08 12:07:08.104  3581  4963 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.github.salomonbrys.kotson.BuilderKt
02-08 12:07:08.104  3581  4963 E AndroidRuntime: 	... 15 more
02-08 12:07:11.272  5077  5077 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-08 12:07:11.694  5077  5137 E SQLiteLog: (284) automatic index on C(manga_id)
02-08 12:07:11.695  5077  5137 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-08 12:07:29.975  5077  5077 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-08 12:07:29.975  5077  5077 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-08 12:07:29.982  5077  5077 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-08 12:07:29.982  5077  5077 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-08 12:07:33.592  5077  5140 E ACRA    : ACRA caught a IllegalStateException for eu.kanade.tachiyomi
02-08 12:07:33.592  5077  5140 E ACRA    : java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
02-08 12:07:33.592  5077  5140 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:3)
02-08 12:07:33.592  5077  5140 E ACRA    : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
02-08 12:07:33.592  5077  5140 E ACRA    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-08 12:07:33.592  5077  5140 E ACRA    : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
02-08 12:07:33.592  5077  5140 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-08 12:07:33.592  5077  5140 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-08 12:07:33.592  5077  5140 E ACRA    : 	at java.lang.Thread.run(Thread.java:920)
02-08 12:07:33.592  5077  5140 E ACRA    : Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/salomonbrys/kotson/BuilderKt;
02-08 12:07:33.592  5077  5140 E ACRA    : 	at eu.kanade.tachiyomi.extension.en.mangarock.MangaRock.searchMangaRequest(MangaRock.kt:113)
02-08 12:07:33.592  5077  5140 E ACRA    : 	at eu.kanade.tachiyomi.source.online.HttpSource.fetchSearchManga(HttpSource.kt:1)
02-08 12:07:33.592  5077  5140 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.globalsearch.GlobalSearchPresenter$$ExternalSyntheticLambda4.call(R8$$SyntheticClass:2)
02-08 12:07:33.592  5077  5140 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:2)
02-08 12:07:33.592  5077  5140 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:1)
02-08 12:07:33.592  5077  5140 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:2)
02-08 12:07:33.592  5077  5140 E ACRA    : 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:4)
02-08 12:07:33.592  5077  5140 E ACRA    : 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:2)
02-08 12:07:33.592  5077  5140 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:2)
02-08 12:07:33.592  5077  5140 E ACRA    : 	... 6 more
02-08 12:07:33.592  5077  5140 E ACRA    : Caused by: java.lang.ClassNotFoundException: com.github.salomonbrys.kotson.BuilderKt
02-08 12:07:33.592  5077  5140 E ACRA    : 	... 15 more
02-08 12:07:35.675  5342  5342 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-08 12:07:35.917  5342  5393 E SQLiteLog: (284) automatic index on C(manga_id)
02-08 12:07:35.917  5342  5393 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.1 (standard, d6386cef4, 74, 2022-02-03T14:45Z)
Android version: 12 (SDK 31)
Android build ID: SQ1D.220105.007
Device brand: google
Device manufacturer: Google
Device name: oriole
Device model: Pixel 6
Device product name: oriole
```
</details>

### Tachiyomi version

0.13.1

### Android version

12

### Device

Google Pixel 6

### Other details

This wasn't an issue in previous versions. 

I sometimes keep old extensions installed, because Tachiyomi can't read previously downloaded chapters without the extension installed. 

If I migrate to another source, the new source would overwrite/download duplicates of the downloaded chapters, which is bad when you particularly have good quality scans saved only to have it overwritten by poor quality scans. 

Workarounds:
Identify which extension causes the crash from logs. Then, go to the extension causing the crash and disable any languages checked. 

Suggestions:
All obsolete extensions should be unchecked/ignored for search by default (maybe make it a toggle in settings). Or handle the exception and/or warn user 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Fixed by 9c426bc216d2ca61dd1168f119b4ddc99e770e47
