### ISSUE TITLE
App crashes when changing views

### ISSUE THREAD

**Issue by DeadyBear** [tachiyomiorg/tachiyomi#6702]
### Steps to reproduce

Open any manga
Change view from portrait to landscape or vice versa

### Expected behavior

The app should not crash when i change between the views

### Actual behavior

The app crashes

### Crash logs
```
--------- beginning of main
02-26 15:14:20.614 22199 22330 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:20.702 22199 22326 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:27.191 22199 22199 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi.debug
02-26 15:14:27.191 22199 22199 E ACRA    : java.lang.NullPointerException: Attempt to read from field 'int android.view.WindowManager$LayoutParams.flags' on a null object reference
02-26 15:14:27.191 22199 22199 E ACRA    : 	at androidx.core.view.WindowInsetsControllerCompat$Impl20.show(WindowInsetsControllerCompat.java:11)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity.setMenuVisibility(ReaderActivity.kt:3)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity.setMenuVisibility$default(ReaderActivity.kt:1)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$ReaderConfig.access$setCutoutShort(ReaderActivity.kt:2)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$ReaderConfig$4.invokeSuspend(ReaderActivity.kt:1)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$ReaderConfig$4.invoke(Unknown Source:12)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$ReaderConfig$4.invoke(Unknown Source:8)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:5)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:11)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:3)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:29)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:3)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:1)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:10)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:1)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:5)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:3)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at kotlinx.coroutines.flow.FlowKt__CollectKt.launchIn(Collect.kt:1)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at kotlinx.coroutines.flow.FlowKt.launchIn(Unknown Source:1)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$ReaderConfig.<init>(ReaderActivity.kt:14)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity.onCreate(ReaderActivity.kt:26)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at android.app.Activity.performCreate(Activity.java:7817)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at android.app.Activity.performCreate(Activity.java:7806)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3424)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3593)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5533)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5441)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:107)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at android.os.Looper.loop(Looper.java:264)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:7684)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:507)
02-26 15:14:27.191 22199 22199 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
02-26 15:14:28.600 22679 22679 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
02-26 15:14:31.039 22679 22744 E SQLiteLog: (284) automatic index on C(manga_id)
02-26 15:14:31.039 22679 22744 E SQLiteLog: (284) automatic index on R(manga_id)
02-26 15:14:31.039 22679 22744 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-26 15:14:32.130 22679 22797 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:32.130 22679 22807 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:32.131 22679 22751 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:32.131 22679 22799 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:32.131 22679 22753 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:32.131 22679 22752 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:32.131 22679 22803 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:32.131 22679 22802 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:32.131 22679 22798 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:32.131 22679 22805 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:32.131 22679 22801 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:32.132 22679 22800 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:32.132 22679 22804 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:32.132 22679 22806 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:32.219 22679 22706 E ion     : ioctl c0044901 failed with code -1: Invalid argument
02-26 15:14:33.811 22679 22797 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:33.812 22679 22800 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:33.813 22679 22753 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
02-26 15:14:33.813 22679 22805 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
App version: 0.13.1-4170 (standard, 2f07f226b, 75, 2022-02-19T21:08Z)
Android version: 10 (SDK 29)
Android build ID: X688B-H659ABCEFGHI-Q-GL-220109V524
Device brand: Infinix
Device manufacturer: INFINIX MOBILITY LIMITED
Device name: Infinix-X688B
Device model: Infinix X688B
Device product name: X688B-GL
```

### Tachiyomi version

r4170

### Android version

10

### Device

infinix X688B

### Other details

The same crash doesn't happen on the other tachiyomi forks, for example tachiyomi OCR and aniyomi  doesn't crash when changing views

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Can't reproduce in newer version.
