### ISSUE TITLE
Save option while reading crashes the app.

### ISSUE THREAD

**Issue by caiuaqui** [tachiyomiorg/tachiyomi#6905]
### Steps to reproduce

1. Open any manga (it doesn't the matter the source)
2. While reading, long press to appear the menu
3.  Select the "Save" option.

### Expected behavior

The app would save the current page I'm reading on the designated folder (on my device, it's the Tachiyomi folder inside the Pictures folder).

### Actual behavior

The app just crashes, sometimes it restarts itself and no image is saved.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/8467625/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.13.2

### Android version

Android 11

### Device

Xiaomi Mi A3

### Other details

This happened right after I updated to the latest version (0.13.2).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
```
04-10 23:41:40.711 26331 26402 E AndroidRuntime: java.io.FileNotFoundException: java.io.FileNotFoundException: No item at content://media/external_primary/images/media/223960
04-10 23:41:40.711 26331 26402 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
04-10 23:41:40.711 26331 26402 E AndroidRuntime: 	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:704)
04-10 23:41:40.711 26331 26402 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1818)
04-10 23:41:40.711 26331 26402 E AndroidRuntime: 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1520)
04-10 23:41:40.711 26331 26402 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.saver.ImageSaver.save(ImageSaver.kt:18)
04-10 23:41:40.711 26331 26402 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderPresenter$saveImage$1.invokeSuspend(ReaderPresenter.kt:8)
04-10 23:41:40.711 26331 26402 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
04-10 23:41:40.711 26331 26402 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
04-10 23:41:40.711 26331 26402 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
04-10 23:41:40.711 26331 26402 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
04-10 23:41:40.711 26331 26402 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
04-10 23:41:40.711 26331 26402 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
04-10 23:41:40.711 26331 26402 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d7ce77d, Dispatchers.IO]
04-10 23:42:36.749 30444 30619 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
```

**Comment by arkon** [comment]
I can make it avoid crashing, but does saving a cover/page ever work for you? Does the app have storage permissions?

**Comment by caiuaqui** [comment]
The app has storage permissions. 
After I updated to the latest version, saving a page would crash the app. Before that, I had no problem whatsoever.

I don't know if this will help, but I tried to disable the storage permissions and reenable, to see if would change anything.
However, the result was the same.

**Comment by caiuaqui** [comment]
After the update to the 0.13.3 version, the crash still happens.

The exception described in the logs is still the same as the previous logs : _ java.io.FileNotFoundException: No item at content://media/external_primary/images/media/224745_

```
04-18 15:53:53.104 30298 30362 E ImageSaver: java.io.FileNotFoundException: java.io.FileNotFoundException: No item at content://media/external_primary/images/media/224745
04-18 15:53:53.104 30298 30362 E ImageSaver: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
04-18 15:53:53.104 30298 30362 E ImageSaver: 	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:704)
04-18 15:53:53.104 30298 30362 E ImageSaver: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1818)
04-18 15:53:53.104 30298 30362 E ImageSaver: 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1520)
04-18 15:53:53.104 30298 30362 E ImageSaver: 	at eu.kanade.tachiyomi.data.saver.ImageSaver.save(ImageSaver.kt:15)
04-18 15:53:53.104 30298 30362 E ImageSaver: 	at eu.kanade.tachiyomi.ui.reader.ReaderPresenter$saveImage$1.invokeSuspend(ReaderPresenter.kt:8)
04-18 15:53:53.104 30298 30362 E ImageSaver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
04-18 15:53:53.104 30298 30362 E ImageSaver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
04-18 15:53:53.104 30298 30362 E ImageSaver: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
04-18 15:53:53.104 30298 30362 E ImageSaver: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
04-18 15:53:53.104 30298 30362 E ImageSaver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
04-18 15:53:53.104 30298 30362 E ImageSaver: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
04-18 15:53:53.111 30298 30362 E ACRA    : ACRA caught a IOException for eu.kanade.tachiyomi
04-18 15:53:53.111 30298 30362 E ACRA    : java.io.IOException: Erro ao salvar a imagem
04-18 15:53:53.111 30298 30362 E ACRA    : 	at eu.kanade.tachiyomi.data.saver.ImageSaver.save(ImageSaver.kt:29)
04-18 15:53:53.111 30298 30362 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderPresenter$saveImage$1.invokeSuspend(ReaderPresenter.kt:8)
04-18 15:53:53.111 30298 30362 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
04-18 15:53:53.111 30298 30362 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
04-18 15:53:53.111 30298 30362 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
04-18 15:53:53.111 30298 30362 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
04-18 15:53:53.111 30298 30362 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
04-18 15:53:53.111 30298 30362 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
04-18 15:53:53.111 30298 30362 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@634841b, Dispatchers.IO]
04-18 15:53:53.414 30439 30439 E .tachiyomi:acr: Not starting debugger since process cannot load the jdwp agent.
04-18 15:53:57.948 30585 30585 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
04-18 15:53:58.747 30585 30709 E SQLiteLog: (284) automatic index on C(manga_id)
04-18 15:53:58.747 30585 30709 E SQLiteLog: (284) automatic index on R(manga_id)
04-18 15:53:58.747 30585 30709 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.3 (standard, 28522f4, 79, 2022-04-15T20:39Z)
Android version: 11 (SDK 30)
Android build ID: qssi-user 11 RKQ1.200903.002 V12.0.18.0.RFQEUXM
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: laurel_sprout
Device model: Mi A3
Device product name: laurel_sprout_eea

```

**Comment by caiuaqui** [comment]
UPDATE:

I believe I found what's causing this error. 
In the Tachiyomi folder inside the Pictures folder, where the images are deposited when using the _Save Image_ option, I have a ``.nomedia`` file.
If I remove this file, the _Save Image_ option functions perfectly otherwise it crashes the app.

However, as I stated, this happened after the update to the 0.13.2 .

**Comment by arkon** [comment]
https://stackoverflow.com/questions/63868535/android-11-media-store-cannot-record-new-videos-on-relative-path-it-works-wit

**Comment by arkon** [comment]
This is supposedly fixed by later revisions of Android 11.
