### ISSUE TITLE
App sometimes crashes on update

### ISSUE THREAD

**Issue by MrAndre96** [tachiyomiorg/tachiyomi#7713]
### Steps to reproduce

1. Open the app
2. Start updating the library / sometimes also on other actions (but the crash does only happen sometimes not always)

### Expected behavior

No crash should happen

### Actual behavior

A crash happens and closes the app

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/9292672/tachiyomi_crash_logs.txt)

### Tachiyomi version

r4739

### Android version

Android 11

### Device

Oneplus 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
```
08-09 17:44:49.449  3916  3916 E ACRA    : java.lang.IllegalArgumentException: Key 309550 was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:25)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:1)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(LazyLayoutMeasureScope.kt:4)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.foundation.lazy.LazyMeasuredItemProvider.getAndMeasure-ZjPyQlc(LazyMeasuredItemProvider.kt:2)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(LazyList.kt:73)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$2$1.invoke(LazyLayout.kt:5)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:5)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:8)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:5)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.foundation.layout.FillModifier.measure-3p2s80s(Size.kt:12)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:5)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:32)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:1)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:1)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.node.LayoutNode.performMeasure-BRTryo0$ui_release(LayoutNode.kt:3)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:18)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.kt:3)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:1)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout-0kLqBqw(MeasureAndLayoutDelegate.kt:8)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout-0kLqBqw(AndroidComposeView.android.kt:2)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.node.LayoutNode.forceRemeasure(LayoutNode.kt:3)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.foundation.lazy.LazyListState.onScroll$foundation_release(LazyListState.kt:6)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.foundation.lazy.LazyListState$scrollableState$1.invoke(LazyListState.kt:2)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.foundation.gestures.DefaultScrollableState$scrollScope$1.scrollBy(ScrollableState.kt:1)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.foundation.gestures.ScrollingLogic.dispatchScroll-f0eR0lY(Scrollable.kt:9)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.foundation.gestures.ScrollDraggableState.dragBy-Uv8p0NA(Scrollable.kt:3)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.foundation.gestures.DraggableKt$draggable$9$2$2.invokeSuspend(Draggable.kt:6)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:2)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:2)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1350)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:1040)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:938)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at android.os.Looper.loop(Looper.java:233)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8010)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
08-09 17:44:49.449  3916  3916 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

What screen are you on when it crashes?

**Comment by MrAndre96** [comment]
Was on the updates screen but it crashes randomly so can't really reproduce it with better steps. Happens around once a week that my app randomly closes itself

**Comment by MrAndre96** [comment]
@arkon it is on the updates screen. When I started the update went to another screen and went back the loading went slow into a crash. Here the logs
[tachiyomi_crash_logs (1).txt](https://github.com/tachiyomiorg/tachiyomi/files/9703218/tachiyomi_crash_logs.1.txt)

**Comment by arkon** [comment]
```
09-21 19:46:11.462  6224  6224 E AndroidRuntime: java.lang.IllegalArgumentException: Key eu.kanade.tachiyomi.extension.en.hiperdex_Idle was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
```

```
10-04 08:08:11.385  6726  6726 E AndroidRuntime: java.lang.IllegalArgumentException: Key updates-338373 was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
```

**Comment by arkon** [comment]
Closing for now, please reopen if it happens again after the build after r5018.
