### ISSUE TITLE
Can't Read/Open downloaded chapter and Crash when open next chapterlibrary

### ISSUE THREAD

**Issue by nurananto** [tachiyomiorg/tachiyomi#7880]
### Steps to reproduce

Read / Open Downloaded chapter
1. Download chapter from bilibili
2. Open it from library

Crash when open next chapter
1. Read next chapter from chapter 0
Deatte hito Tsuki de Zecchou Jorei! (mangadex)

### Expected behavior

Read / Open downloaded chapter
1. Read manga

Crash when open next chapter
1. Read chapter 1

### Actual behavior

Read / Open downloaded chapter
1. Infinite loading / Never Ending loading

Crash when open next chapter
1. tachiyomi force closed at some point

### Crash logs

08-28 06:26:21.774 19856 19856 E AndroidRuntime: FATAL EXCEPTION: main
08-28 06:26:21.774 19856 19856 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 19856
08-28 06:26:21.774 19856 19856 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 21, Size: 21
08-28 06:26:21.774 19856 19856 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
08-28 06:26:21.774 19856 19856 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonAdapter.onLongStripSplit(WebtoonAdapter.kt:3)
08-28 06:26:21.774 19856 19856 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer.$r8$lambda$54RlNE1Z21GomngDIJ1EzRby29o(WebtoonViewer.kt:2)
08-28 06:26:21.774 19856 19856 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer$$ExternalSyntheticLambda0.run(Unknown Source:6)
08-28 06:26:21.774 19856 19856 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-28 06:26:21.774 19856 19856 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-28 06:26:21.774 19856 19856 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-28 06:26:21.774 19856 19856 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-28 06:26:21.774 19856 19856 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
08-28 06:26:21.774 19856 19856 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-28 06:26:21.774 19856 19856 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
08-28 06:26:21.774 19856 19856 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
08-28 06:27:09.941  4385  4385 E AndroidRuntime: FATAL EXCEPTION: main
08-28 06:27:09.941  4385  4385 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 4385
08-28 06:27:09.941  4385  4385 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 21, Size: 21
08-28 06:27:09.941  4385  4385 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
08-28 06:27:09.941  4385  4385 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonAdapter.onLongStripSplit(WebtoonAdapter.kt:3)
08-28 06:27:09.941  4385  4385 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer.$r8$lambda$54RlNE1Z21GomngDIJ1EzRby29o(WebtoonViewer.kt:2)
08-28 06:27:09.941  4385  4385 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonViewer$$ExternalSyntheticLambda0.run(Unknown Source:6)
08-28 06:27:09.941  4385  4385 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-28 06:27:09.941  4385  4385 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-28 06:27:09.941  4385  4385 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-28 06:27:09.941  4385  4385 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-28 06:27:09.941  4385  4385 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
08-28 06:27:09.941  4385  4385 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-28 06:27:09.941  4385  4385 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
08-28 06:27:09.941  4385  4385 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
--------- beginning of main
08-28 13:35:45.060  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:35:45.118  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:36:08.113  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:36:08.238  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:36:25.714  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:36:25.787  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:36:36.598  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:36:36.670  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:36:43.816  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:36:44.184  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:38:09.552  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:38:09.976  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:39:32.229  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:39:32.301  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:39:32.435  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -101
08-28 13:39:38.055  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:39:38.418  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:39:41.551  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:39:41.799  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:39:45.054  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:39:45.113  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:40:08.331  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:40:08.404  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:40:14.115  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:40:14.478  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:41:19.910  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:41:19.965  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:41:22.749  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:41:22.824  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:41:49.979  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:41:50.142  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:41:55.014  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
08-28 13:41:55.271  7014  8009 E chromium: [ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -100
App version: 0.13.6-4841 (standard, 1948d55d5, 82, 2022-08-27T22:12Z)
Android version: 12 (SDK 32)
Android build ID: SQ3A.220705.003
Device brand: POCO
Device manufacturer: Xiaomi
Device name: vayu
Device model: M2102J20SG
Device product name: vayu_global

### Tachiyomi version

r4841

### Android version

Android 12.1

### Device

Poco X3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by nurananto** [comment]
Video when reading downloaded chapter from bilibili

https://photos.app.goo.gl/3iVN9qwhguZ6enew7
