### ISSUE TITLE
Tachiyomi crashes when you remove multiple items from a category at the same time.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#7997]
### Steps to reproduce

1. Open tachiyomi.
2. Open any category.
3. Remove multiple items from this category.

### Expected behavior

Nothing happens.

### Actual behavior

Tachiyomi crashes.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/9546307/tachiyomi_crash_logs.txt)

### Tachiyomi version

Preview r4904

### Android version

Android 11

### Device

Redmi Note 9 Pro Max

### Other details

https://user-images.githubusercontent.com/63903377/189610647-81e213fb-debd-412c-a62b-e5feab33b89f.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Can't seem to reproduce this, and the provided crash logs don't seem relevant. Do you have newer logs?

**Comment by arkon** [comment]
Does this still happen for you?

**Comment by THElegend5** [comment]
> Does this still happen for you?

Yep still happening as of latest preview.

**Comment by arkon** [comment]
Can you share a backup of your library?

**Comment by THElegend5** [comment]
> Can you share a backup of your library?

https://1drv.ms/u/s!AueB9tr4szgbgelwvJIB7jfj6kgtEg?e=0Zf5zM
Here you go.

**Comment by arkon** [comment]
From provided logs:

```
09-19 02:11:20.146 19324 19492 E CursorWindow: Failed to read row 613, column 0 from a CursorWindow which has 613 rows, 21 columns.
09-19 02:11:20.187 19324 19555 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi.debug
09-19 02:11:20.187 19324 19555 E ACRA    : java.lang.NullPointerException
09-19 02:11:20.187 19324 19555 E ACRA    : 	at eu.kanade.tachiyomi.app.CategoriesQueriesImpl$getCategories$1$$ExternalSyntheticOutline0.m(R8$$SyntheticClass:1)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at eu.kanade.tachiyomi.app.MangasQueriesImpl$getLibrary$1.invoke(DatabaseImpl.kt:20)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
09-19 02:11:20.187 19324 19555 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2c9dded, Dispatchers.IO]
```

Can't reproduce it with the given backup either though. Dose it happen consistently for anything? Did you try reinstalling?

**Comment by THElegend5** [comment]
> From provided logs:
> 
> ```
> 09-19 02:11:20.146 19324 19492 E CursorWindow: Failed to read row 613, column 0 from a CursorWindow which has 613 rows, 21 columns.
> 09-19 02:11:20.187 19324 19555 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi.debug
> 09-19 02:11:20.187 19324 19555 E ACRA    : java.lang.NullPointerException
> 09-19 02:11:20.187 19324 19555 E ACRA    : 	at eu.kanade.tachiyomi.app.CategoriesQueriesImpl$getCategories$1$$ExternalSyntheticOutline0.m(R8$$SyntheticClass:1)
> 09-19 02:11:20.187 19324 19555 E ACRA    : 	at eu.kanade.tachiyomi.app.MangasQueriesImpl$getLibrary$1.invoke(DatabaseImpl.kt:20)
> 09-19 02:11:20.187 19324 19555 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
> 09-19 02:11:20.187 19324 19555 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
> 09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
> 09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
> 09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
> 09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
> 09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
> 09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
> 09-19 02:11:20.187 19324 19555 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2c9dded, Dispatchers.IO]
> ```
> 
> Can't reproduce it with the given backup either though. Dose it happen consistently for anything? Did you try reinstalling?

Happens consistently as shown in the video on removing multiple entries in a cat at once, just reinstalled tachi 5003.

**Comment by arkon** [comment]
Still can't reproduce, not sure if anyone else can?

**Comment by THElegend5** [comment]
@arkon The crash seems to have stopped in r5062 if you only removing multiple items from a category, but doing so causes the library to become quite laggy and causes the category button to take quite some time to respond and adding them back to the category now causes tachiyomi to crash. This also stops the crash from happening at all and the lag going away if you got to a different tab and come back as is the case in #8222.

~~Also the crash seems to only be happening 80 percent of the time after the re add , other time tachiyomi somehow manages to not crash.~~ I have been unable to reproduce the crash in the video to get a crash log and the time in the video is the last time it crashed along with 2-3 times before the video.

https://user-images.githubusercontent.com/63903377/196087073-915e5013-5865-4ce4-974f-c0456fcaef40.mp4

**Comment by THElegend5** [comment]
@arkon this crash started happening again in r5071 after cold boot and stuff was fixed and I can still reproduce it consistently.

**Comment by ARiyou2000** [comment]
This crash is happening to me frequently as well.
It's happen either wgen you choose multiple item and click `Remove from library` or Click `🖤` button in specific item.

App version: 0.14.3 (standard, 817418f, 93, 2023-01-07T17:15Z)
Android version: 8.0.0 (SDK 26)
Android build ID: RNE-L21 8.0.0.351(C185)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWRNE
Device model: RNE-L21
Device product name: RNE-L21

**Comment by humdogm** [comment]
Getting the same issue as the above latest commenter, where it happens when I remove a single manga from my library from the manga's screen when pressing the heart button.
Here's the logcat I took of the crash:
```
01-31 00:39:27.394 28372 28521 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi
01-31 00:39:27.394 28372 28521 E ACRA    : java.lang.NullPointerException
01-31 00:39:27.394 28372 28521 E ACRA    :      at eu.kanade.tachiyomi.app.LibraryViewQueriesImpl$library$1.invoke(DatabaseImpl.kt:19)
01-31 00:39:27.394 28372 28521 E ACRA    :      at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
01-31 00:39:27.394 28372 28521 E ACRA    :      at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
01-31 00:39:27.394 28372 28521 E ACRA    :      at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invoke(FlowExtensions.kt:13)
01-31 00:39:27.394 28372 28521 E ACRA    :      at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
01-31 00:39:27.394 28372 28521 E ACRA    :      at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
01-31 00:39:27.394 28372 28521 E ACRA    :      at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
01-31 00:39:27.394 28372 28521 E ACRA    :      at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$$inlined$map$1$2.emit(Collect.kt:76)
01-31 00:39:27.394 28372 28521 E ACRA    :      at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:2)
01-31 00:39:27.394 28372 28521 E ACRA    :      at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:19)
01-31 00:39:27.394 28372 28521 E ACRA    :      at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
01-31 00:39:27.394 28372 28521 E ACRA    :      at com.squareup.sqldelight.runtime.coroutines.FlowQuery$asFlow$1.invokeSuspend(FlowExtensions.kt:130)
01-31 00:39:27.394 28372 28521 E ACRA    :      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
01-31 00:39:27.394 28372 28521 E ACRA    :      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
01-31 00:39:27.394 28372 28521 E ACRA    :      at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
01-31 00:39:27.394 28372 28521 E ACRA    :      at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
01-31 00:39:27.394 28372 28521 E ACRA    :      at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
01-31 00:39:27.394 28372 28521 E ACRA    :      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
01-31 00:39:27.394 28372 28521 E ACRA    :      Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(eu.kanade.tachiyomi.ui.library.LibraryTab:eu.kanade.tachiyomi.ui.library.LibraryScreenModel:default:ScreenModelCoroutineScope), StandaloneCoroutine{Cancelling}@dd39bbc, Dispatchers.IO]
```

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10543629/tachiyomi_crash_logs.txt)

**Comment by scb261** [comment]
Going to gather info from support channel in this comment from different users

<details>
  <summary>Case 1 - 4157 entries</summary>
  
Discord message - https://discord.com/channels/349436576037732353/349436576037732355/1071321668770873384

> Been crashing a lot lately
Whenever I remove a manga from bookmark/catagory

![](https://cdn.discordapp.com/attachments/349436576037732355/1071321668531789895/Screenshot_2023-02-04-12-17-59-71_afd66b7916d19a60815f56273408b73e.jpg)

Device and app info:

```
App version: 0.14.3 (standard, 817418f, 93, 2023-01-07T17:15Z)
Android version: 12 (SDK 31)
Android build ID: RMX3241_11_C.06
Device brand: realme
Device manufacturer: realme
Device name: RE513CL1
Device model: RMX3241
Device product name: RMX3241
```

> Realme 8 5g 
Mediatek dimensity 700 
Android 12 6gb ram
</details>

**Comment by Turhvjbufv** [comment]
Also happens to me

**Comment by Claydeut** [comment]
Same thing here
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/12411339/tachiyomi_crash_logs.txt)

**Comment by natyoufri** [comment]
same for me for a long time, will happen even with only one remove. however, i observed that it dit not happens when removing a manga from the libray but it does happens when removing the manga from the source.
