### ISSUE TITLE
Tachiyomi Preview r4929 Error 

### ISSUE THREAD

**Issue by TheGoldenSun** [tachiyomiorg/tachiyomi#8049]
### Steps to reproduce

1. Improve Tachiyomi preview
2. Improve searching manga stories in libraries
3. Improve loading sequence within tachiyomi preview 

### Expected behavior

I've been encountering several issues whenever I tap into tachiyomi preview app.

### Actual behavior

Whenever I migrate the same manga I wanted to read to the next manga extension it always kicks me out of the tachiyomi preview app automatically for no reason, this has been an ongoing issue for me everytime I try migrating something from my libraries. 

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/9620899/tachiyomi_crash_logs.txt)

### Tachiyomi version

R4929

### Android version

Android 11

### Device

Galaxy A02 

### Other details

I hope you look into this issue since it become bothersome to me when using tachiyomi preview version r4929. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
```
09-21 18:45:06.825  4122 28135 E ACRA    : ACRA caught a IllegalStateException for eu.kanade.tachiyomi.debug
09-21 18:45:06.825  4122 28135 E ACRA    : java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
09-21 18:45:06.825  4122 28135 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:19)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at java.lang.Thread.run(Thread.java:923)
09-21 18:45:06.825  4122 28135 E ACRA    : Caused by: java.lang.VerifyError: Superclass eu.kanade.tachiyomi.source.model.Filter$Header of eu.kanade.tachiyomi.extension.all.mangareaderto.Note is declared final (declaration of 'eu.kanade.tachiyomi.extension.all.mangareaderto.Note' appears in /data/app/~~D1eXb1YFouMCNPet2L7vDg==/eu.kanade.tachiyomi.extension.all.mangareaderto-bKuVKLXuuZz9wDnp0gZGag==/base.apk)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at eu.kanade.tachiyomi.extension.all.mangareaderto.MangaReaderFactory.createSources(MangaReaderFactory.kt:7)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at eu.kanade.tachiyomi.extension.util.ExtensionLoader.loadExtension(ExtensionLoader.kt:510)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at eu.kanade.tachiyomi.extension.util.ExtensionLoader.access$loadExtension(ExtensionLoader.kt:3)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at eu.kanade.tachiyomi.extension.util.ExtensionLoader$loadExtensions$1$deferred$1$1.invokeSuspend(ExtensionLoader.kt:24)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:155)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:30)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:77)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:7)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at eu.kanade.tachiyomi.extension.util.ExtensionLoader.loadExtensions(ExtensionLoader.kt:74)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at eu.kanade.tachiyomi.extension.ExtensionManager.<init>(ExtensionManager.kt:114)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at eu.kanade.tachiyomi.AppModule$registerInjectables$8.invoke(AppModule.kt:9)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1$$special$$inlined$getOrPut$lambda$1.invoke(DefaultRegistrar.kt:5)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1.invoke(DefaultRegistrar.kt:51)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at uy.kohesive.injekt.registry.default.DefaultRegistrar.getInstance(DefaultRegistrar.kt:16)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at eu.kanade.tachiyomi.AppModule$registerInjectables$9.invoke(AppModule.kt:20)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1$$special$$inlined$getOrPut$lambda$1.invoke(DefaultRegistrar.kt:5)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1.invoke(DefaultRegistrar.kt:51)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at uy.kohesive.injekt.registry.default.DefaultRegistrar.getInstance(DefaultRegistrar.kt:16)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at eu.kanade.domain.DomainModule$registerInjectables$42.invoke(DomainModule.kt:14)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at uy.kohesive.injekt.registry.default.DefaultRegistrar.getInstance(DefaultRegistrar.kt:16)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at eu.kanade.domain.DomainModule$registerInjectables$32.invoke(DomainModule.kt:31)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at uy.kohesive.injekt.registry.default.DefaultRegistrar.getInstance(DefaultRegistrar.kt:16)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at uy.kohesive.injekt.api.InjektScope.getInstance(Unknown Source:7)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at eu.kanade.tachiyomi.ui.library.LibraryPresenter.<init>(LibraryPresenter.kt:119)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at eu.kanade.tachiyomi.ui.library.LibraryController.createPresenter(LibraryController.kt:4)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at eu.kanade.tachiyomi.ui.base.presenter.NucleusConductorDelegate.getPresenter(NucleusConductorDelegate.kt:7)
09-21 18:45:06.825  4122 28135 E ACRA    : 	at eu.kanade.tachiyomi.ui.base.presenter.NucleusConductorLifecycleListener.postCreateView(NucleusConductorLifecycleListener.kt:19)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at com.bluelinelabs.conductor.Controller.inflate(Controller.java:123)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:153)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:25)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at com.bluelinelabs.conductor.Router.setBackstack(Router.java:489)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at eu.kanade.tachiyomi.ui.base.controller.ConductorExtensionsKt.setRoot(ConductorExtensions.kt:36)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at eu.kanade.tachiyomi.ui.main.MainActivity.$r8$lambda$hwjF1asI1b7qEu84oFM9aVYY964(MainActivity.kt:125)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at com.google.android.material.navigation.NavigationBarView$1.onMenuItemSelected(NavigationBarView.java:24)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:5)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:15)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:14)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at com.google.android.material.navigation.NavigationBarView.setSelectedItemId(NavigationBarView.java:14)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at eu.kanade.tachiyomi.ui.main.MainActivity.setSelectedNavItem(MainActivity.kt:11)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at eu.kanade.tachiyomi.ui.main.MainActivity.moveToStartScreen(MainActivity.kt:3)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at eu.kanade.tachiyomi.ui.main.MainActivity.onCreate(MainActivity.kt:369)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at android.app.Activity.performCreate(Activity.java:8207)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at android.app.Activity.performCreate(Activity.java:8191)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3808)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4011)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at android.os.Looper.loop(Looper.java:246)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8633)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
09-21 18:45:06.826  4122 28135 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
