### ISSUE TITLE
Tachiyomi Backup Issues

### ISSUE THREAD

**Issue by Superiorepicness67** [tachiyomiorg/tachiyomi#8138]
### Steps to reproduce

I wanted to transfer my current library and organization to a new phone. 
1. I went to settings to make a backup
2. Chose the location of the backup
3. click create back up
4. Waited for the download to finish
5. Looked at the file and found that it had 0mB and was unreadable

### Expected behavior

I expected there to be a useable backup of my library and everything with it.  

### Actual behavior

When I check the file, all that  I found was an unusable file. 

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/9694609/tachiyomi_crash_logs.txt)

```
--------- beginning of main
10-02 19:20:26.247 24240 24240 E DecorView: mWindow.mActivityCurrentConfig is null
10-02 19:20:26.283 24240 24240 E DecorView: mWindow.mActivityCurrentConfig is null
10-02 19:20:28.457 24240 24240 E ViewRootImpl: sendUserActionEvent() mView returned.
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: Work [ id=967f2369-3dcc-4812-b0b3-3532d397247e, tags={ eu.kanade.tachiyomi.data.backup.BackupCreatorJob, BackupCreator:manual } ] failed because it threw an exception/error
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Failed to allocate a 268435472 byte allocation with 8388608 free bytes and 124MB until OOM, target footprint 414628376, growth limit 536870912
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:4)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:48)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:1)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:1)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at java.lang.Thread.run(Thread.java:919)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 268435472 byte allocation with 8388608 free bytes and 124MB until OOM, target footprint 414628376, growth limit 536870912
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at kotlinx.serialization.protobuf.internal.ByteArrayOutput.ensureCapacity(Streams.kt:2)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at kotlinx.serialization.protobuf.internal.ByteArrayOutput.write(Streams.kt:8)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at kotlinx.serialization.protobuf.internal.ProtobufWriter.writeOutput(ProtobufWriter.kt:4)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at kotlinx.serialization.protobuf.internal.ProtobufWriter.writeOutput(ProtobufWriter.kt:2)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at kotlinx.serialization.protobuf.internal.ObjectEncoder.endEncode(ProtobufEncoding.kt:2)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at kotlinx.serialization.protobuf.internal.ProtobufTaggedEncoder.endStructure(ProtobufTaggedEncoder.kt:3)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at eu.kanade.tachiyomi.data.backup.full.models.BackupManga$$serializer.serialize(BackupManga.kt:1)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at eu.kanade.tachiyomi.data.backup.full.models.BackupManga$$serializer.serialize(BackupManga.kt:2)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at kotlinx.serialization.protobuf.internal.ProtobufEncoder.encodeSerializableValue(ProtobufEncoding.kt:4)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at kotlinx.serialization.protobuf.internal.ProtobufTaggedEncoder.encodeSerializableElement(ProtobufTaggedEncoder.kt:3)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at kotlinx.serialization.internal.CollectionLikeSerializer.serialize(CollectionSerializers.kt:5)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at kotlinx.serialization.protobuf.internal.ProtobufEncoder.encodeSerializableValue(ProtobufEncoding.kt:4)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at kotlinx.serialization.protobuf.internal.ProtobufTaggedEncoder.encodeSerializableElement(ProtobufTaggedEncoder.kt:3)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at eu.kanade.tachiyomi.data.backup.full.models.Backup.write$Self(Backup.kt:1)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at eu.kanade.tachiyomi.data.backup.full.models.BackupSerializer.serialize(BackupSerializer.kt:1)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at eu.kanade.tachiyomi.data.backup.full.models.BackupSerializer.serialize(BackupSerializer.kt:2)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at kotlinx.serialization.protobuf.internal.ProtobufEncoder.encodeSerializableValue(ProtobufEncoding.kt:4)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at kotlinx.serialization.protobuf.ProtoBuf.encodeToByteArray(ProtoBuf.kt:3)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at eu.kanade.tachiyomi.data.backup.full.FullBackupManager.createBackup(FullBackupManager.kt:33)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at eu.kanade.tachiyomi.data.backup.BackupCreatorJob.doWork(BackupCreatorJob.kt:22)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	at androidx.work.Worker$1.run(Worker.java:1)
10-02 19:27:33.490 24240 24847 E WM-WorkerWrapper: 	... 3 more
App version: 0.13.6 (standard, 1f79444, 82, 2022-08-14T15:52Z)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.A205USQSBBVC1
Device brand: samsung
Device manufacturer: samsung
Device name: a20p
Device model: SM-A205U
Device product name: a20psq
```

### Tachiyomi version

0.13.6

### Android version

Android 10

### Device

Samsung A20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [x] I will fill out all of the requested information in this form.

**Comment by Superiorepicness67** [comment]
https://stackoverflow.com/questions/32244851/androidjava-lang-outofmemoryerror-failed-to-allocate-a-23970828-byte-allocatio

Would this help at all?

**Comment by arkon** [comment]
The app already has `android:largeHeap` configured. The app was never really designed for use with large libraries. That combined with devices with low amounts of memory exacerbates the problem. Having a smaller library would help you in the short term.

I'm not sure how the app would handle this better though, we'd need to allocate the objects before writing it to a file regardless.

**Comment by Superiorepicness67** [comment]
Okay, thanks for the update. Let me know if you have any tips.

**Comment by Superiorepicness67** [comment]
How small of a library is "smaller"?

**Comment by arkon** [comment]
#7966 would help with this.
