### ISSUE TITLE
Unable to move category

### ISSUE THREAD

**Issue by Helltraitor** [tachiyomiorg/tachiyomi#8372]
### Steps to reproduce

1.Create new category after updating
2. Try to move prelate element to bottom 

### Expected behavior

Element goes down and we can change categories order

### Actual behavior

Application crashes

### Crash logs

--------- beginning of main
10-31 00:55:07.702  5141  5141 E anade.tachiyom: Invalid ID 0x00000000.
10-31 00:55:09.754  5141  5228 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect()
10-31 00:55:10.617  5141  5228 E BLASTBufferQueue: BLASTBufferItemConsumer::onDisconnect()
10-31 00:55:12.621 14055 14055 E anade.tachiyom: Unknown bits set in runtime_flags: 0x40000000
10-31 00:55:12.885 14055 14055 E anade.tachiyom: Invalid ID 0x00000000.
10-31 00:55:12.896 14055 14093 E SQLiteLog: (283) recovered 11 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
--------- beginning of system
10-31 00:55:12.902 14055 14055 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
10-31 00:55:13.498 14055 14055 E anade.tachiyom: ofbOpen failed with error=No such file or directory
10-31 00:55:13.498 14055 14055 E anade.tachiyom: sysOpen failed with error=No such file or directory
10-31 00:55:13.673 14261 14261 E .tachiyomi:acr: Unknown bits set in runtime_flags: 0x40000000
10-31 00:55:13.814 14055 14224 E SQLiteLog: (284) automatic index on C(manga_id)
10-31 00:55:13.814 14055 14224 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-31 00:55:13.880 14261 14284 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
10-31 00:55:34.867 14261 14433 E ACRA    : Failed to send crash reports for /data/user/0/eu.kanade.tachiyomi/app_ACRA-approved/2022-10-31T00:32:11.288+03:00.stacktrace
10-31 00:55:34.867 14261 14433 E ACRA    : org.acra.sender.ReportSenderException: Policy marked this task as incomplete. ACRA will try to send this report again.
10-31 00:55:34.867 14261 14433 E ACRA    : 	at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:184)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at org.acra.sender.ReportDistributor.distribute(ReportDistributor.kt:47)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at org.acra.sender.SendingConductor.sendReports(SendingConductor.kt:96)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at org.acra.sender.JobSenderService$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:37)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at java.lang.Thread.run(Thread.java:1012)
10-31 00:55:34.867 14261 14433 E ACRA    : Caused by: org.acra.sender.ReportSenderException: Error while sending JSON report via Http PUT
10-31 00:55:34.867 14261 14433 E ACRA    : 	at org.acra.sender.HttpSender.send(HttpSender.kt:18)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at org.acra.sender.HttpSender.send(HttpSender.kt:1)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:66)
10-31 00:55:34.867 14261 14433 E ACRA    : 	... 4 more
10-31 00:55:34.867 14261 14433 E ACRA    : Caused by: java.net.SocketTimeoutException: Read timed out
10-31 00:55:34.867 14261 14433 E ACRA    : 	at java.net.SocketInputStream.socketRead0(Native Method)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at java.net.SocketInputStream.read(SocketInputStream.java:173)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at java.net.SocketInputStream.read(SocketInputStream.java:143)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at org.acra.http.BaseHttpRequest.writeContent(BaseHttpRequest.kt:29)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at org.acra.http.BaseHttpRequest.send(BaseHttpRequest.kt:243)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at org.acra.sender.HttpSender.sendWithoutAttachments(HttpSender.kt:56)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at org.acra.sender.HttpSender.sendHttpRequests(HttpSender.kt:66)
10-31 00:55:34.867 14261 14433 E ACRA    : 	at org.acra.sender.HttpSender.send(HttpSender.kt:17)
10-31 00:55:34.867 14261 14433 E ACRA    : 	... 6 more
10-31 00:55:35.233 14055 14209 E ACRA    : ACRA caught a IndexOutOfBoundsException for eu.kanade.tachiyomi
10-31 00:55:35.233 14055 14209 E ACRA    : java.lang.IndexOutOfBoundsException: Index: 12, Size: 11
10-31 00:55:35.233 14055 14209 E ACRA    : 	at java.util.ArrayList.add(ArrayList.java:483)
10-31 00:55:35.233 14055 14209 E ACRA    : 	at eu.kanade.domain.category.interactor.ReorderCategory$await$2.invokeSuspend(ReorderCategory.kt:161)
10-31 00:55:35.233 14055 14209 E ACRA    : 	at eu.kanade.domain.category.interactor.ReorderCategory$await$2.invoke(ReorderCategory.kt:13)
10-31 00:55:35.233 14055 14209 E ACRA    : 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
10-31 00:55:35.233 14055 14209 E ACRA    : 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
10-31 00:55:35.233 14055 14209 E ACRA    : 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
10-31 00:55:35.233 14055 14209 E ACRA    : 	at eu.kanade.tachiyomi.util.lang.CoroutinesExtensionsKt.withNonCancellableContext(CoroutinesExtensions.kt:3)
10-31 00:55:35.233 14055 14209 E ACRA    : 	at eu.kanade.domain.category.interactor.ReorderCategory.await(ReorderCategory.kt:14)
10-31 00:55:35.233 14055 14209 E ACRA    : 	at eu.kanade.tachiyomi.ui.category.CategoryPresenter$moveDown$1.invokeSuspend(CategoryPresenter.kt:49)
10-31 00:55:35.233 14055 14209 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
10-31 00:55:35.233 14055 14209 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
10-31 00:55:35.233 14055 14209 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
10-31 00:55:35.233 14055 14209 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
10-31 00:55:35.233 14055 14209 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
10-31 00:55:35.233 14055 14209 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
10-31 00:55:35.233 14055 14209 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@416fdc0, Dispatchers.IO]
10-31 00:55:38.220 14660 14660 E anade.tachiyom: Unknown bits set in runtime_flags: 0x40000000
10-31 00:55:38.423 14660 14715 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
10-31 00:55:38.492 14660 14660 E anade.tachiyom: Invalid ID 0x00000000.
10-31 00:55:38.502 14660 14660 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
10-31 00:55:38.906 14660 14875 E SQLiteLog: (284) automatic index on C(manga_id)
10-31 00:55:38.906 14660 14875 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-31 00:55:38.914 14660 14660 E anade.tachiyom: ofbOpen failed with error=No such file or directory
10-31 00:55:38.914 14660 14660 E anade.tachiyom: sysOpen failed with error=No such file or directory
App version: 0.14.1 (standard, 5b12c14, 90, 2022-10-29T15:53Z)
Android version: 12 (SDK 31)
Android build ID: RMX3081_11_C.21
Device brand: realme
Device manufacturer: realme
Device name: RMX3081L1
Device model: RMX3081
Device product name: RMX3081RU

### Tachiyomi version

0.14.1

### Android version

Android 12

### Device

Realme 8 Pro

### Other details

After taken top element to down, all starts to work. My opinion: maybe application forgets to do something with indexes in db

Guys in Discord support ask me to create this issue (I was trying to reproduce, but I couldn't)

Anyway, you have my crash dump so you can trust that I don't try to spend your time 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Helltraitor** [comment]
It's kind a dangling, and appears again for me, so I can provide a new logs

Check database using. Seems like problem is around it

```
--------- beginning of system
10-31 01:11:29.964 23024 23024 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
--------- beginning of main
10-31 01:13:18.920 25018 25018 E anade.tachiyom: Unknown bits set in runtime_flags: 0x40000000
10-31 01:13:19.120 25018 25052 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
10-31 01:13:19.159 25018 25018 E anade.tachiyom: Invalid ID 0x00000000.
10-31 01:13:19.170 25018 25018 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
10-31 01:13:19.622 25018 25018 E anade.tachiyom: ofbOpen failed with error=No such file or directory
10-31 01:13:19.622 25018 25018 E anade.tachiyom: sysOpen failed with error=No such file or directory
10-31 01:13:19.633 25018 25130 E SQLiteLog: (284) automatic index on C(manga_id)
10-31 01:13:19.633 25018 25130 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.1 (standard, 5b12c14, 90, 2022-10-29T15:53Z)
Android version: 12 (SDK 31)
Android build ID: RMX3081_11_C.21
Device brand: realme
Device manufacturer: realme
Device name: RMX3081L1
Device model: RMX3081
Device product name: RMX3081RU
```
