### ISSUE TITLE
App crashed when searching, updating, and migrating. 

### ISSUE THREAD

**Issue by JackSkel** [tachiyomiorg/tachiyomi#8400]
### Steps to reproduce

1. Open app
2. Update via global update
3. Then a few seconds the app closes. Same goes with migrating or searching. 

### Expected behavior

It should finish updating the manga in my library and will proceed to downloading the new chapters. 

### Actual behavior

After migrating or updating the app suddenly closes/crashes

### Crash logs
```
--------- beginning of main
11-01 11:44:27.709  1459  1459 E anade.tachiyom: LoadAppImageStartupCache enabled : 1
11-01 11:44:27.709  1459  1459 E anade.tachiyom: Unknown bits set in runtime_flags: 0x8000
11-01 11:44:27.711  1459  1459 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
11-01 11:44:27.732  1459  1481 E BehaviorCollectManager: Fail to acquire dataAnalyzerService...
11-01 11:44:27.748  1459  1490 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@9e8351a
11-01 11:44:27.837  1459  1507 E SQLiteLog: (283) recovered 169 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
11-01 11:44:27.909  1459  1459 E anade.tachiyom: Dex checksum does not match for dex: /system/product/app/WebViewGoogle/WebViewGoogle.apk.Expected: 3834107321, actual: 3168972864
11-01 11:44:28.270  1459  1607 E SQLiteLog: (284) automatic index on C(manga_id)
11-01 11:44:28.270  1459  1607 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
11-01 11:44:28.283  1459  1459 E HwViewGroupImpl: parse speed value length error
11-01 11:44:39.639  1459  1459 E RtgSchedManager: endActivityTransaction: margin state not match
11-01 11:44:39.642  1459  1459 E RtgSchedManager: endActivityTransaction: margin state not match
11-01 11:44:39.663  1459  1459 E RtgSchedManager: endActivityTransaction: margin state not match
11-01 11:45:51.759  1459  1605 E CursorWindow: Failed to read row 2493, column 0 from a CursorWindow which has 2493 rows, 13 columns.
11-01 11:45:51.761  1459  1459 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi
11-01 11:45:51.761  1459  1459 E ACRA    : java.lang.NullPointerException
11-01 11:45:51.761  1459  1459 E ACRA    : 	at eu.kanade.tachiyomi.app.UpdatesViewQueriesImpl$updates$1.invoke(DatabaseImpl.kt:19)
11-01 11:45:51.761  1459  1459 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
11-01 11:45:51.761  1459  1459 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
11-01 11:45:51.761  1459  1459 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
11-01 11:45:51.761  1459  1459 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
11-01 11:45:51.761  1459  1459 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
11-01 11:45:51.761  1459  1459 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
11-01 11:45:51.761  1459  1459 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
11-01 11:45:51.761  1459  1459 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
11-01 11:45:51.761  1459  1459 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c029f85, Dispatchers.Main.immediate]
11-01 11:45:51.866  3414  3414 E .tachiyomi:acr: LoadAppImageStartupCache enabled : 1
11-01 11:45:51.866  3414  3414 E .tachiyomi:acr: Unknown bits set in runtime_flags: 0x8000
11-01 11:45:51.869  3414  3414 E .tachiyomi:acr: Not starting debugger since process cannot load the jdwp agent.
11-01 11:45:51.905  3414  3465 E BehaviorCollectManager: Fail to acquire dataAnalyzerService...
11-01 11:45:52.085  3414  3494 E SQLiteLog: (283) recovered 850 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
11-01 11:45:52.111  3414  3414 E .tachiyomi:acr: Dex checksum does not match for dex: /system/product/app/WebViewGoogle/WebViewGoogle.apk.Expected: 3834107321, actual: 3168972864
11-01 11:49:42.507  7733  7733 E anade.tachiyom: LoadAppImageStartupCache enabled : 1
11-01 11:49:42.507  7733  7733 E anade.tachiyom: Unknown bits set in runtime_flags: 0x8000
11-01 11:49:42.510  7733  7733 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
11-01 11:49:42.529  7733  7752 E BehaviorCollectManager: Fail to acquire dataAnalyzerService...
11-01 11:49:42.684  7733  7760 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@9e8351a
11-01 11:49:42.813  7733  7785 E SQLiteLog: (283) recovered 1 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
11-01 11:49:43.274  7733  7733 E HwViewGroupImpl: parse speed value length error
11-01 11:49:43.302  7733  7835 E SQLiteLog: (284) automatic index on C(manga_id)
11-01 11:49:43.302  7733  7835 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)
Android version: 10 (SDK 29)
Android build ID: VOG-L29 10.1.0.148(C636E11R1P3)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWVOG
Device model: VOG-L29
Device product name: VOG-L29
```

### Tachiyomi version

0.14.2

### Android version

Android 10

### Device

Huawei p30 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
Same crash from support channel on discord when updating a category with 244 entries in it

> I am facing a problem. Whenever I refresh the category (this means it's updating right) after refreshing for a while suddenly the tachiyomi app crashes and automatically starts updating from the start again.

> It used to update 2k without any problem. But now i update normally 200 - 900

> For me the app doesn't crashes during searching or migrating.
But searching and going latest source is taking a lot of time after the update.

<details>
  <summary>Crashlog</summary>

```
--------- beginning of main
01-18 08:32:38.928  8960  8960 E BoostFramework: BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
01-18 08:33:50.788  8960 10471 E chromium: [ERROR:simple_file_enumerator.cc(21)] opendir /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/wasm: No such file or directory (2)
01-18 08:33:50.788  8960 10471 E chromium: [ERROR:simple_index_file.cc(614)] Could not reconstruct index from disk
01-18 08:33:50.818  8960  8960 E ResourceType: Style contains key with bad entry: 0x0101056c
01-18 08:33:50.819  8960  8960 E ResourceType: Style contains key with bad entry: 0x0101056d
01-18 08:33:50.819  8960  8960 E ResourceType: Style contains key with bad entry: 0x0101058c
01-18 08:33:50.819  8960  8960 E ResourceType: Style contains key with bad entry: 0x01010604
01-18 08:33:50.819  8960  8960 E ResourceType: Style contains key with bad entry: 0x01010605
01-18 08:33:50.819  8960  8960 E ResourceType: Style contains key with bad entry: 0x0101056d
01-18 08:33:50.819  8960  8960 E ResourceType: Style contains key with bad entry: 0x0101058c
01-18 08:33:50.819  8960  8960 E ResourceType: Style contains key with bad entry: 0x01010604
01-18 08:33:50.819  8960  8960 E ResourceType: Style contains key with bad entry: 0x01010605
01-18 08:33:50.819  8960  8960 E ResourceType: Style contains key with bad entry: 0x0101056c
01-18 08:33:50.820  8960  8960 E ResourceType: Style contains key with bad entry: 0x0101056d
01-18 08:33:50.820  8960  8960 E ResourceType: Style contains key with bad entry: 0x0101058c
01-18 08:33:50.820  8960  8960 E ResourceType: Style contains key with bad entry: 0x01010604
01-18 08:33:50.820  8960  8960 E ResourceType: Style contains key with bad entry: 0x01010605
01-18 08:33:50.820  8960  8960 E ResourceType: Style contains key with bad entry: 0x0101056c
01-18 08:33:50.820  8960  8960 E ResourceType: Style contains key with bad entry: 0x0101056d
01-18 08:33:50.820  8960  8960 E ResourceType: Style contains key with bad entry: 0x0101058c
01-18 08:33:50.820  8960  8960 E ResourceType: Style contains key with bad entry: 0x01010604
01-18 08:33:50.820  8960  8960 E ResourceType: Style contains key with bad entry: 0x01010605
01-18 08:33:50.897  8960 10488 E libEGL  : validate_display:99 error 3008 (EGL_BAD_DISPLAY)
01-18 08:34:20.840  8960 10486 E ConnectivityManager.CallbackHandler: callback not found for RELEASED message
01-18 08:36:33.452 11390 11420 E SQLiteLog: (283) recovered 363 frames from WAL file /data/data/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
01-18 08:36:33.468 11390 11390 E ResourceType: Style contains key with bad entry: 0x0101056c
01-18 08:36:33.470 11390 11390 E ResourceType: Style contains key with bad entry: 0x0101056d
01-18 08:36:33.470 11390 11390 E ResourceType: Style contains key with bad entry: 0x0101058c
01-18 08:36:33.470 11390 11390 E ResourceType: Style contains key with bad entry: 0x01010604
01-18 08:36:33.470 11390 11390 E ResourceType: Style contains key with bad entry: 0x01010605
01-18 08:36:33.476 11390 11390 E ResourceType: Style contains key with bad entry: 0x0101056d
01-18 08:36:33.476 11390 11390 E ResourceType: Style contains key with bad entry: 0x0101058c
01-18 08:36:33.476 11390 11390 E ResourceType: Style contains key with bad entry: 0x01010604
01-18 08:36:33.476 11390 11390 E ResourceType: Style contains key with bad entry: 0x01010605
01-18 08:36:35.984 11390 11487 E SQLiteLog: (284) automatic index on C(manga_id)
01-18 08:36:35.984 11390 11487 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
01-18 08:36:43.279 11390 11390 E BoostFramework: BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
01-18 08:37:58.287 11390 11390 E ResourceType: Style contains key with bad entry: 0x0101056c
01-18 08:37:58.288 11390 11390 E ResourceType: Style contains key with bad entry: 0x0101056d
01-18 08:37:58.288 11390 11390 E ResourceType: Style contains key with bad entry: 0x0101058c
01-18 08:37:58.288 11390 11390 E ResourceType: Style contains key with bad entry: 0x01010604
01-18 08:37:58.288 11390 11390 E ResourceType: Style contains key with bad entry: 0x01010605
01-18 08:37:58.288 11390 11390 E ResourceType: Style contains key with bad entry: 0x0101056d
01-18 08:37:58.288 11390 11390 E ResourceType: Style contains key with bad entry: 0x0101058c
01-18 08:37:58.288 11390 11390 E ResourceType: Style contains key with bad entry: 0x01010604
01-18 08:37:58.288 11390 11390 E ResourceType: Style contains key with bad entry: 0x01010605
01-18 08:37:58.289 11390 11390 E ResourceType: Style contains key with bad entry: 0x0101056c
01-18 08:37:58.289 11390 11390 E ResourceType: Style contains key with bad entry: 0x0101056d
01-18 08:37:58.289 11390 11390 E ResourceType: Style contains key with bad entry: 0x0101058c
01-18 08:37:58.289 11390 11390 E ResourceType: Style contains key with bad entry: 0x01010604
01-18 08:37:58.289 11390 11390 E ResourceType: Style contains key with bad entry: 0x01010605
01-18 08:37:58.289 11390 11390 E ResourceType: Style contains key with bad entry: 0x0101056c
01-18 08:37:58.289 11390 11390 E ResourceType: Style contains key with bad entry: 0x0101056d
01-18 08:37:58.289 11390 11390 E ResourceType: Style contains key with bad entry: 0x0101058c
01-18 08:37:58.289 11390 11390 E ResourceType: Style contains key with bad entry: 0x01010604
01-18 08:37:58.289 11390 11390 E ResourceType: Style contains key with bad entry: 0x01010605
01-18 08:37:58.381 11390 13967 E libEGL  : validate_display:99 error 3008 (EGL_BAD_DISPLAY)
01-18 08:38:28.281 11390 11651 E ConnectivityManager.CallbackHandler: callback not found for RELEASED message
01-18 08:42:34.733 11390 11487 E CursorWindow: Failed to read row 2536, column 0 from a CursorWindow which has 2536 rows, 13 columns.
01-18 08:42:34.799 11390 11390 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi
01-18 08:42:34.799 11390 11390 E ACRA    : java.lang.NullPointerException
01-18 08:42:34.799 11390 11390 E ACRA    : 	at eu.kanade.tachiyomi.app.UpdatesViewQueriesImpl$updates$1.invoke(DatabaseImpl.kt:19)
01-18 08:42:34.799 11390 11390 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
01-18 08:42:34.799 11390 11390 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
01-18 08:42:34.799 11390 11390 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
01-18 08:42:34.799 11390 11390 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
01-18 08:42:34.799 11390 11390 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
01-18 08:42:34.799 11390 11390 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
01-18 08:42:34.799 11390 11390 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
01-18 08:42:34.799 11390 11390 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
01-18 08:42:34.799 11390 11390 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9c76e05, Dispatchers.Main.immediate]
01-18 08:42:35.552 16307 16323 E SQLiteLog: (283) recovered 192 frames from WAL file /data/data/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
01-18 08:42:39.186 16413 16441 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
01-18 08:42:39.206 16413 16413 E ResourceType: Style contains key with bad entry: 0x0101056c
01-18 08:42:39.209 16413 16413 E ResourceType: Style contains key with bad entry: 0x0101056d
01-18 08:42:39.209 16413 16413 E ResourceType: Style contains key with bad entry: 0x0101058c
01-18 08:42:39.209 16413 16413 E ResourceType: Style contains key with bad entry: 0x01010604
01-18 08:42:39.209 16413 16413 E ResourceType: Style contains key with bad entry: 0x01010605
01-18 08:42:39.222 16413 16413 E ResourceType: Style contains key with bad entry: 0x0101056d
01-18 08:42:39.222 16413 16413 E ResourceType: Style contains key with bad entry: 0x0101058c
01-18 08:42:39.222 16413 16413 E ResourceType: Style contains key with bad entry: 0x01010604
01-18 08:42:39.222 16413 16413 E ResourceType: Style contains key with bad entry: 0x01010605
01-18 08:42:41.132 16413 16558 E SQLiteLog: (284) automatic index on C(manga_id)
01-18 08:42:41.132 16413 16558 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
--------- beginning of system
01-18 08:42:53.345 16413 16413 E ResourceType: Style contains key with bad entry: 0x0101056c
01-18 08:42:53.346 16413 16413 E ResourceType: Style contains key with bad entry: 0x0101056d
01-18 08:42:53.346 16413 16413 E ResourceType: Style contains key with bad entry: 0x0101058c
01-18 08:42:53.346 16413 16413 E ResourceType: Style contains key with bad entry: 0x01010604
01-18 08:42:53.346 16413 16413 E ResourceType: Style contains key with bad entry: 0x01010605
01-18 08:42:53.346 16413 16413 E ResourceType: Style contains key with bad entry: 0x0101056d
01-18 08:42:53.346 16413 16413 E ResourceType: Style contains key with bad entry: 0x0101058c
01-18 08:42:53.346 16413 16413 E ResourceType: Style contains key with bad entry: 0x01010604
01-18 08:42:53.346 16413 16413 E ResourceType: Style contains key with bad entry: 0x01010605
01-18 08:42:53.347 16413 16413 E ResourceType: Style contains key with bad entry: 0x0101056c
01-18 08:42:53.347 16413 16413 E ResourceType: Style contains key with bad entry: 0x0101056d
01-18 08:42:53.347 16413 16413 E ResourceType: Style contains key with bad entry: 0x0101058c
01-18 08:42:53.347 16413 16413 E ResourceType: Style contains key with bad entry: 0x01010604
01-18 08:42:53.347 16413 16413 E ResourceType: Style contains key with bad entry: 0x01010605
01-18 08:42:53.347 16413 16413 E ResourceType: Style contains key with bad entry: 0x0101056c
01-18 08:42:53.347 16413 16413 E ResourceType: Style contains key with bad entry: 0x0101056d
01-18 08:42:53.347 16413 16413 E ResourceType: Style contains key with bad entry: 0x0101058c
01-18 08:42:53.347 16413 16413 E ResourceType: Style contains key with bad entry: 0x01010604
01-18 08:42:53.347 16413 16413 E ResourceType: Style contains key with bad entry: 0x01010605
01-18 08:42:53.432 16413 16821 E libEGL  : validate_display:99 error 3008 (EGL_BAD_DISPLAY)
01-18 08:42:58.761 16413 16612 E GetManga: kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelling}@aa31358
01-18 08:42:58.767 16413 16561 E UpdateChapter: kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelling}@aa31358
01-18 08:42:58.767 16413 16561 E MangaRepositoryImpl: kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelling}@aa31358
01-18 08:42:58.768 16413 16597 E UpdateChapter: kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelling}@aa31358
01-18 08:42:58.768 16413 16597 E MangaRepositoryImpl: kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelling}@aa31358
01-18 08:43:00.191 16413 16413 E BoostFramework: BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
App version: 0.14.3 (standard, 817418f, 93, 2023-01-07T17:15Z)
Android version: 7.0 (SDK 24)
Android build ID: NRD90M.N920CXXU5CVG2
Device brand: samsung
Device manufacturer: samsung
Device name: noblelte
Device model: SM-N920C
Device product name: nobleltejv
```

</details>

<details>
  <summary>Installed extensions</summary>

![](https://media.discordapp.net/attachments/349436576037732355/1065102348554346506/Screenshot_20230118-085455.png)

![](https://media.discordapp.net/attachments/349436576037732355/1065102348931829900/Screenshot_20230118-085502.png)

![](https://media.discordapp.net/attachments/349436576037732355/1065102349263175730/Screenshot_20230118-085508.png)

![](https://media.discordapp.net/attachments/349436576037732355/1065102349611311114/Screenshot_20230118-085547.png)

</details>

Device and app info from crashlog:

```
App version: 0.14.3 (standard, 817418f, 93, 2023-01-07T17:15Z)
Android version: 7.0 (SDK 24)
Android build ID: NRD90M.N920CXXU5CVG2
Device brand: samsung
Device manufacturer: samsung
Device name: noblelte
Device model: SM-N920C
Device product name: nobleltejv
```

To be continued: the user promised to tell later today if it crashes on the same manga or not

**Comment by harleymerlin** [comment]
I'm having this issue too. Whenever I update my library, it would keep crashing and force the app to close. And also, whenever I close the app, the chapter keep scrolling back to the front page of the chapter. For example, I've read half of chapter 89, when the app close, it will be back at the first page of chapter 89.


> 
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10564295/tachiyomi_crash_logs.txt)

> 
[tachiyomi_2023-02-02_10-45.proto.gz](https://github.com/tachiyomiorg/tachiyomi/files/10564303/tachiyomi_2023-02-02_10-45.proto.gz)



> App version: 0.14.3 (standard, 817418f, 93, 2023-01-07T17:15Z)
Android version: 12 (SDK 31)
Android build ID: SKQ1.211006.001 test-keys
Device brand: POCO
Device manufacturer: Xiaomi
Device name: vayu
Device model: M2102J20SG
Device product name: vayu_global

**Comment by harleymerlin** [comment]
I'm having this issue too. Whenever I update my library, it would keep crashing and force the app to close. And also, whenever I close the app, the chapter keep scrolling back to the front page of the chapter. For example, I've read half of chapter 89, when the app close, it will be back at the first page of chapter 89.


> 
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10564503/tachiyomi_crash_logs.txt)

> 
[Uploading tachiyomi_2023-02-02_10-45.proto.gz…]()


App version: 0.14.3 (standard, 817418f, 93, 2023-01-07T17:15Z)
Android version: 12 (SDK 31)
Android build ID: SKQ1.211006.001 test-keys
Device brand: POCO
Device manufacturer: Xiaomi
Device name: vayu
Device model: M2102J20SG
Device product name: vayu_global

**Comment by harleymerlin** [comment]
I'm having this issue too. Whenever I update my library, it would keep crashing and force the app to close. And also, whenever I close the app, the chapter keep scrolling back to the front page of the chapter. For example, I've read half of chapter 89, when the app close, it will be back at the first page of chapter 89.

> 
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10564569/tachiyomi_crash_logs.txt)

> 
[tachiyomi_2023-02-02_10-45.proto.gz](https://github.com/tachiyomiorg/tachiyomi/files/10564571/tachiyomi_2023-02-02_10-45.proto.gz)

App version: 0.14.3 (standard, 817418f, 93, 2023-01-07T17:15Z)
Android version: 12 (SDK 31)
Android build ID: SKQ1.211006.001 test-keys
Device brand: POCO
Device manufacturer: Xiaomi
Device name: vayu
Device model: M2102J20SG
Device product name: vayu_global

**Comment by elchinky** [comment]
Having the issue where when trying to do global update, it will update for a while then the app crashes. Upon opening the app again the update will resume.

Doesn't crash at the same number ex. (376/2778), (404/2778)

Used to be able to update 2k+relatively quick, has gotten a lot slower. Also searching has gotten really slow compared to before.

My app does not crash when searching or migrating. Only when updating library. Has only started happening since 03/02/23

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10607761/tachiyomi_crash_logs.txt)

![Extensions](https://user-images.githubusercontent.com/124420564/216750798-d9276ac0-01a4-4525-889e-042cb7123e61.jpg)


App version: 0.14.3 (standard, 817418f, 93, 2023-01-07T17:15Z)
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.014.G9860ZHS3GWA1
Device brand: samsung
Device manufacturer: samsung
Device name: y2q
Device model: SM-G9860
Device product name: y2qzhx

**Comment by gigutsy** [comment]
Tachiyomi app crashes when updating lubrary enteries and it crashes when the enteries read 200/x
Been having this issue for sometime now

**Comment by arkon** [comment]
I _think_ this is mitigated already in preview with a smaller amount of entries being shown in the updates screen/widget.
