### ISSUE TITLE
Tablet UI: App crashes in Settings if the General category is selected first

### ISSUE THREAD

**Issue by kiriya-aoi** [tachiyomiorg/tachiyomi#8563]
### Steps to reproduce

1. Use tablet UI
2. Go to Settings
3. Tap General

### Expected behavior

Nothing. General is already open when entering Settings in tablet mode.

### Actual behavior

App crashes.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10047607/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.14.2

### Android version

Android 12

### Device

Galaxy Tab S7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
```
11-19 12:19:48.385 32759 32759 E ACRA    : ACRA caught a IllegalArgumentException for eu.kanade.tachiyomi
11-19 12:19:48.385 32759 32759 E ACRA    : java.lang.IllegalArgumentException: Key eu.kanade.presentation.more.settings.screen.SettingsGeneralScreen:transition:lifecycle was used multiple times 
11-19 12:19:48.385 32759 32759 E ACRA    : 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:90)
11-19 12:19:48.385 32759 32759 E ACRA    : 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:7)
11-19 12:19:48.385 32759 32759 E ACRA    : 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:102)
11-19 12:19:48.385 32759 32759 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:85)
11-19 12:19:48.385 32759 32759 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
11-19 12:19:48.385 32759 32759 E ACRA    : 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:218)
```
