### ISSUE TITLE
Occasionally scroll right then crush on MainActivity

### ISSUE THREAD

**Issue by Terrible-Tornado** [tachiyomiorg/tachiyomi#8658]
### Steps to reproduce

Only remember that the last step is scroll to right

### Expected behavior

Scroll to the right page or nothing happen

### Actual behavior

App crush and go back to android launcher

### Crash logs

FATAL EXCEPTION: main
Process: eu.kanade.tachiyomi.debug, PID: 4634
java.lang.NoSuchMethodError: No direct method <init>(ZZLandroidx/compose/ui/window/SecureFlagPolicy;ZILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Landroidx/compose/ui/window/DialogProperties; or its super classes (declaration of 'androidx.compose.ui.window.DialogProperties' appears in /data/app/eu.kanade.tachiyomi.debug-8DVS5d-8c-vhrPMEvtFQgg==/base.apk!classes19.dex)
	at com.mikepenz.aboutlibraries.ui.compose.LibrariesKt.LicenseDialog(Libraries.kt:160)
	at com.mikepenz.aboutlibraries.ui.compose.LibrariesKt.Libraries(Libraries.kt:124)
	at com.mikepenz.aboutlibraries.ui.compose.LibrariesKt$Libraries$3.invoke(Unknown Source:50)
	at com.mikepenz.aboutlibraries.ui.compose.LibrariesKt$Libraries$3.invoke(Unknown Source:16)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:145)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2367)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2634)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3250)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3228)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:336)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3228)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3193)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:753)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1008)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:125)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:533)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:502)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:693)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@cebbb4, androidx.compose.ui.platform.MotionDurationScaleImpl@66ef3dd, StandaloneCoroutine{Cancelling}@5795b52, AndroidUiDispatcher@1eb0e23]

### Tachiyomi version

0.13.6

### Android version

Android 9.0

### Device

Emulator Google Pixel 2

### Other details

Hope these infos could help.

Don't know how to reproduce the crash in the latest version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Doesn't seem relevant with newer versions, but thanks.
