### ISSUE TITLE
Clear database screen crashes 

### ISSUE THREAD

**Issue by mobi2002** [tachiyomiorg/tachiyomi#8851]
### Steps to reproduce

Go to advanced settings
Double tap on clear database 

### Expected behavior

Opens up the clear database screen 

### Actual behavior

Crashes

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10365548/tachiyomi_crash_logs.txt)

### Tachiyomi version

r5383

### Android version

Android 13

### Device

Tecno spark 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
```
01-07 10:14:38.318 31887 31887 E ACRA    : java.lang.IllegalArgumentException: Key eu.kanade.presentation.more.settings.screen.ClearDatabaseScreen:transition:lifecycle was used multiple times 
01-07 10:14:38.318 31887 31887 E ACRA    : 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:90)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:7)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:102)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:85)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:218)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:11)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:34)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:17)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:827)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:942)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:201)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at android.os.Looper.loop(Looper.java:288)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:7893)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-07 10:14:38.318 31887 31887 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```
