### ISSUE TITLE
Crash around categories screen

### ISSUE THREAD

**Issue by mobi2002** [tachiyomiorg/tachiyomi#8861]
### Steps to reproduce

Go to more
Double tap on categories
Press back button in the categories screen 

### Expected behavior

Goes back to more

### Actual behavior

Crash

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10367672/tachiyomi_crash_logs.txt)

### Tachiyomi version

r5405

### Android version

Android 13

### Device

Tecno spark 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
```
01-08 08:56:55.068 14162 14162 E ACRA    : java.lang.IllegalStateException: ReceiveChannel.consumeAsFlow can be collected just once
01-08 08:56:55.068 14162 14162 E ACRA    : 	at kotlinx.coroutines.flow.ChannelAsFlow.markConsumed(Channels.kt:27)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at kotlinx.coroutines.flow.ChannelAsFlow.collect(Channels.kt:6)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invokeSuspend(Merge.kt:47)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Unknown Source:8)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Unknown Source:4)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:10)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest.flowCollect(Merge.kt:7)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlow.kt:6)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:33)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:15)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:3)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:942)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:201)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at android.os.Looper.loop(Looper.java:288)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:7893)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-08 08:56:55.068 14162 14162 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
01-08 08:56:55.068 14162 14162 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@e9d58e0, 
```
