### ISSUE TITLE
Crash on browse source search

### ISSUE THREAD

**Issue by glavius007** [tachiyomiorg/tachiyomi#9008]
### Steps to reproduce

> I search something
>I quickly correct the search 
>click in a manga
>click to open
> error mesage

### Expected behavior

open normaly

### Actual behavior

error mesage

### Crash logs

```
--------- beginning of main
01-31 02:59:13.422 26369 26369 E tachiyomi.debu: Unknown bits set in runtime_flags: 0x8000
01-31 02:59:13.426 26369 26369 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
01-31 02:59:13.498 26369 26388 E ANDR-PERF: IPerf:: Perf HAL Service is not available.
01-31 02:59:13.498 26369 26388 E ANDR-PERF: IPerf:: Perf HAL Service is not available.
01-31 02:59:13.499 26369 26388 E ANDR-PERF: IPerf:: Perf HAL Service is not available.
01-31 02:59:14.427 26369 26414 E SQLiteLog: (283) recovered 673 frames from WAL file /data/data/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
01-31 02:59:28.609 26369 26369 E DecorView: mWindow.mActivityCurrentConfig is null
01-31 02:59:28.667 26369 26369 E DecorView: mWindow.mActivityCurrentConfig is null
01-31 02:59:32.202 26369 26369 E DecorView: mWindow.mActivityCurrentConfig is null
01-31 02:59:32.469 26369 26369 E DecorView: mWindow.mActivityCurrentConfig is null
01-31 02:59:33.234 26369 26369 E DecorView: mWindow.mActivityCurrentConfig is null
01-31 02:59:33.619 26369 26369 E DecorView: mWindow.mActivityCurrentConfig is null
01-31 02:59:34.002 26369 26369 E DecorView: mWindow.mActivityCurrentConfig is null
01-31 02:59:35.115 26369 26369 E ViewRootImpl: sendUserActionEvent() mView returned.
01-31 02:59:50.299 26369 26369 E StandaloneCoroutine: Failed to get manga URL
01-31 02:59:50.299 26369 26369 E StandaloneCoroutine: kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelling}@8d2c9de
01-31 03:00:35.384 26369 26369 E DecorView: mWindow.mActivityCurrentConfig is null
01-31 03:00:35.453 26369 26369 E DecorView: mWindow.mActivityCurrentConfig is null
01-31 03:00:36.173 26369 26369 E ViewRootImpl: sendUserActionEvent() mView returned.
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: java.lang.IllegalArgumentException: Key Screen#1:transition:lifecycle was used multiple times 
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:71)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:7)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:94)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:81)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:218)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:9)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:34)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:13)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:994)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at android.view.Choreographer.doCallbacks(Choreographer.java:794)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at android.view.Choreographer.doFrame(Choreographer.java:725)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at android.os.Handler.handleCallback(Handler.java:883)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at android.os.Looper.loop(Looper.java:237)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at android.app.ActivityThread.main(ActivityThread.java:7814)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
01-31 03:00:36.579 26369 26369 E GlobalExceptionHandler: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@ac8352d, androidx.compose.ui.platform.MotionDurationScaleImpl@5408a62, StandaloneCoroutine{Cancelling}@70f7f3, AndroidUiDispatcher@497ccb0]
01-31 03:00:36.827 26793 26793 E g:error_handle: Unknown bits set in runtime_flags: 0x8000
01-31 03:00:36.832 26793 26793 E g:error_handle: Not starting debugger since process cannot load the jdwp agent.
01-31 03:00:36.860 26793 26819 E ANDR-PERF: IPerf:: Perf HAL Service is not available.
01-31 03:00:36.861 26793 26819 E ANDR-PERF: IPerf:: Perf HAL Service is not available.
01-31 03:00:36.863 26793 26819 E ANDR-PERF: IPerf:: Perf HAL Service is not available.
01-31 03:00:37.113 26793 26829 E SQLiteLog: (283) recovered 380 frames from WAL file /data/data/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
App version: 0.14.3-5488 (standard, f2c48480b, 94, 2023-01-28T21:09Z)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.A115MUBU2AUD2
Device brand: samsung
Device manufacturer: samsung
Device name: a11q
Device model: SM-A115M
Device product name: a11qub
```

```
--------- beginning of main
01-31 03:35:35.072 26808 26808 E tachiyomi.debu: Unknown bits set in runtime_flags: 0x8000
01-31 03:35:35.081 26808 26808 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
01-31 03:35:35.117 26808 26839 E ANDR-PERF: IPerf:: Perf HAL Service is not available.
01-31 03:35:35.118 26808 26839 E ANDR-PERF: IPerf:: Perf HAL Service is not available.
01-31 03:35:35.119 26808 26839 E ANDR-PERF: IPerf:: Perf HAL Service is not available.
01-31 03:35:36.020 26808 26865 E SQLiteLog: (283) recovered 90 frames from WAL file /data/data/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
01-31 03:35:45.642 26808 26808 E ViewRootImpl@70e02b6[MainActivity]: Surface is not valid.
01-31 03:35:45.712 26808 26808 E ViewRootImpl@70e02b6[MainActivity]: Surface is not valid.
01-31 03:36:39.381 26808 26808 E DecorView: mWindow.mActivityCurrentConfig is null
01-31 03:36:39.413 26808 26808 E DecorView: mWindow.mActivityCurrentConfig is null
01-31 03:36:40.446 26808 26808 E DecorView: mWindow.mActivityCurrentConfig is null
01-31 03:36:40.572 26808 26808 E ViewRootImpl: sendUserActionEvent() mView returned.
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: java.lang.IllegalArgumentException: Key Screen#0:transition:lifecycle was used multiple times 
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:71)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:7)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:94)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:81)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:218)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:9)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:34)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:13)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:994)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at android.view.Choreographer.doCallbacks(Choreographer.java:794)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at android.view.Choreographer.doFrame(Choreographer.java:725)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at android.os.Handler.handleCallback(Handler.java:883)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at android.os.Looper.loop(Looper.java:237)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at android.app.ActivityThread.main(ActivityThread.java:7814)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
01-31 03:37:07.146 26808 26808 E GlobalExceptionHandler: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@3d0ef05, androidx.compose.ui.platform.MotionDurationScaleImpl@ba77b5a, StandaloneCoroutine{Cancelling}@f81218b, AndroidUiDispatcher@eb5d268]
01-31 03:37:07.341 27690 27690 E g:error_handle: Unknown bits set in runtime_flags: 0x8000
01-31 03:37:07.346 27690 27690 E g:error_handle: Not starting debugger since process cannot load the jdwp agent.
01-31 03:37:07.374 27690 27709 E ANDR-PERF: IPerf:: Perf HAL Service is not available.
01-31 03:37:07.375 27690 27709 E ANDR-PERF: IPerf:: Perf HAL Service is not available.
01-31 03:37:07.376 27690 27709 E ANDR-PERF: IPerf:: Perf HAL Service is not available.
01-31 03:37:07.623 27690 27716 E SQLiteLog: (283) recovered 20 frames from WAL file /data/data/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
App version: 0.14.3-5488 (standard, f2c48480b, 94, 2023-01-28T21:09Z)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.A115MUBU2AUD2
Device brand: samsung
Device manufacturer: samsung
Device name: a11q
Device model: SM-A115M
Device product name: a11qub
```

### Tachiyomi version

0.14.3

### Android version

androide 10 

### Device

Samsung a11

### Other details

is it's 4 o'clock at night and I will not respond until 13:00 in brazil time  
good night 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jjjjbow** [comment]
就是，笑死了。
