### ISSUE TITLE
The app crashes and kicks me out

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi#9067]
### Steps to reproduce

1. Sign in to install 
2. Log in to an external source you added
3.He does not bring me to the source and takes me out

### Expected behavior

It should take me to the external resource that you added

### Actual behavior

But he did not interfere with me, but there was a crash with the application and he took me out 

### Crash logs

```
--------- beginning of main
02-11 10:14:37.190 26872 26915 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
02-11 10:14:37.192 26872 26913 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
02-11 10:14:37.337 26872 26915 E SQLiteLog: (284) automatic index on C(anime_id)
02-11 10:14:37.337 26872 26915 E SQLiteLog: (284) automatic index on animes_categories(anime_id)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: Could not open log file: /data/user/0/xyz.jmir.tachiyomi.mi.debug/files/.com.google.firebase.crashlytics.files.v2:xyz.jmir.tachiyomi.mi.debug/open-sessions/63E7405D0076000168F84486BF7124AB/userlog
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: java.io.FileNotFoundException: /data/user/0/xyz.jmir.tachiyomi.mi.debug/files/.com.google.firebase.crashlytics.files.v2:xyz.jmir.tachiyomi.mi.debug/open-sessions/63E7405D0076000168F84486BF7124AB/userlog.tmp: open failed: ENOENT (No such file or directory)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at libcore.io.IoBridge.open(IoBridge.java:574)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.metadata.QueueFile.<init>(QueueFile.java:50)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.metadata.QueueFileLogStore.openLogFile(QueueFileLogStore.java:9)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.metadata.QueueFileLogStore.writeToLog(QueueFileLogStore.java:1)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.metadata.LogFileManager.writeToLog(LogFileManager.java:3)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.CrashlyticsController$5.call(CrashlyticsController.java:19)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.then(CrashlyticsBackgroundWorker.java:3)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.1:27)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:3)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:6)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at java.lang.Thread.run(Thread.java:1012)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at libcore.io.Linux.open(Native Method)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7887)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	at libcore.io.IoBridge.open(IoBridge.java:560)
02-11 10:14:37.361 26872 26898 E FirebaseCrashlytics: 	... 13 more
App version: 0.14.2.0-5879 (standard, 45ceb2219, 93, 2023-01-14T01:30Z)
Android version: 12 (SDK 31)
Android build ID: SKQ1.211103.001
Device brand: lge
Device manufacturer: LGE
Device name: timelm
Device model: LM-V600
Device product name: timelm
```

### Tachiyomi version

0.14.4

### Android version

Android 12

### Device

LG V60 5G

### Other details

https://user-images.githubusercontent.com/87826849/218245918-e9ace2e5-9d55-4d60-9a21-45a6feeb25f6.mp4

Record a video of the problem 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment]
> 02-11 10:14:37.337 26872 26915 E SQLiteLog: (284) automatic index on animes_categories(anime_id)

> App version: 0.14.2.0-5879 (standard, 45ceb22, 93, 2023-01-14T01:30Z)

Go to the aniyomi github

**Comment by arkon** [comment]
Your video is of Tachiyomi but your crash logs are from Aniyomi.

Please create an issue with the proper logs, and after making sure you've updated your app and extensions.

**Comment by yemenihandsome** [comment]
@arkon I know that there are faults in Tachiyomi, aniyomi , and Tachiyomi SY. I encountered the same error in all applications, but Tachiyomi does not show me the crash report.
