### ISSUE TITLE
App Crashes after Opening&Closing multiple Extensions' Settings

### ISSUE THREAD

**Issue by someonenameguy** [tachiyomiorg/tachiyomi#9110]
### Steps to reproduce

Go to Browse Tab.
Open Extensions Tab.
Press on extension's settings.
Exit back to extensions tab.
Repeat opening and closing extension settings [In my testing I open and close multiple different extensions)

### Expected behavior

Opening and closing setting continuously without crashing.

### Actual behavior

The app crashes after some number of extensions.

### Crash logs

[Crash Log.txt](https://github.com/tachiyomiorg/tachiyomi/files/10776398/Crash.Log.txt)

### Tachiyomi version

0.14.4

### Android version

Android 13

### Device

Samsung Note 20 Ultra 5G

### Other details

Video of me trying to set multiple extension settings [Use random User-agent] and the app crashing[At 5:36].
https://drive.google.com/file/d/1Un-s5VTvzHwfeI_-3htbhfRAHa2-KRQo/view?usp=drivesdk

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
```
02-19 13:04:47.966  3762  3762 E ACRA    : ACRA caught a IllegalArgumentException for eu.kanade.tachiyomi
02-19 13:04:47.966  3762  3762 E ACRA    : java.lang.IllegalArgumentException: Key eu.kanade.tachiyomi.ui.browse.extension.details.ExtensionDetailsScreen:transition:lifecycle was used multiple times 
02-19 13:04:47.966  3762  3762 E ACRA    : 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:71)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:7)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:94)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:81)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:218)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:9)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:34)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:13)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:847)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:942)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:226)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at android.os.Looper.loop(Looper.java:313)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8741)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
02-19 13:04:47.966  3762  3762 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```
