### ISSUE TITLE
Shikimori tracker exception is uncaught and crashes app

### ISSUE THREAD

**Issue by txomon** [tachiyomiorg/tachiyomi#9347]
### Steps to reproduce

1. Have shikimori tracker set up
2. ???
3. The app crashes

I'm afraid I have no idea what's wrong with shikimori. But this is continuously crashing. I suppose the problem is located at https://github.com/tachiyomiorg/tachiyomi/blob/7e56cba060becf083b568be2bc5e5fec354f25a1/app/src/main/java/eu/kanade/tachiyomi/data/track/shikimori/ShikimoriInterceptor.kt#L29

### Expected behavior

The shikimori tracker should report an error

### Actual behavior

The app crashes

### Crash logs

```04-16 16:37:57.173  9846 10105 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
04-16 16:37:57.173  9846 10105 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 9846
04-16 16:37:57.173  9846 10105 E AndroidRuntime: kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $
04-16 16:37:57.173  9846 10105 E AndroidRuntime: JSON input:
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:1)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:2)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:57)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:15)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:117)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:46)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:10)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:23)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:1)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:2)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:73)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:31)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at eu.kanade.tachiyomi.data.track.shikimori.ShikimoriInterceptor.intercept(ShikimoriInterceptor.kt:161)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:63)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:113)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:46)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-16 16:37:57.173  9846 10105 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:920)
04-16 16:37:57.174  9846 10105 E ACRA    : ACRA caught a JsonDecodingException for eu.kanade.tachiyomi
04-16 16:37:57.174  9846 10105 E ACRA    : kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $
04-16 16:37:57.174  9846 10105 E ACRA    : JSON input:
04-16 16:37:57.174  9846 10105 E ACRA    :      at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:1)
04-16 16:37:57.174  9846 10105 E ACRA    :      at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:2)
04-16 16:37:57.174  9846 10105 E ACRA    :      at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:57)
04-16 16:37:57.174  9846 10105 E ACRA    :      at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:15)
04-16 16:37:57.174  9846 10105 E ACRA    :      at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:117)
04-16 16:37:57.174  9846 10105 E ACRA    :      at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:46)
04-16 16:37:57.174  9846 10105 E ACRA    :      at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:10)
04-16 16:37:57.174  9846 10105 E ACRA    :      at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:23)
04-16 16:37:57.174  9846 10105 E ACRA    :      at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:1)
04-16 16:37:57.174  9846 10105 E ACRA    :      at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:2)
04-16 16:37:57.174  9846 10105 E ACRA    :      at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:73)
04-16 16:37:57.174  9846 10105 E ACRA    :      at kotlinx.serialization.json.Json.decodeFromString(Json.kt:31)
04-16 16:37:57.174  9846 10105 E ACRA    :      at eu.kanade.tachiyomi.data.track.shikimori.ShikimoriInterceptor.intercept(ShikimoriInterceptor.kt:161)
04-16 16:37:57.174  9846 10105 E ACRA    :      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
04-16 16:37:57.174  9846 10105 E ACRA    :      at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:63)
04-16 16:37:57.174  9846 10105 E ACRA    :      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:156)
04-16 16:37:57.174  9846 10105 E ACRA    :      at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:113)
04-16 16:37:57.174  9846 10105 E ACRA    :      at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:46)
04-16 16:37:57.174  9846 10105 E ACRA    :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-16 16:37:57.174  9846 10105 E ACRA    :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-16 16:37:57.174  9846 10105 E ACRA    :      at java.lang.Thread.run(Thread.java:920)
```

### Tachiyomi version

Stable 0.14.5

### Android version

Android 12

### Device

Ulefone Armor Pad

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by txomon** [comment]
The current fix https://github.com/tachiyomiorg/tachiyomi/commit/564a0980b99183bb2b73999c17a4c6603c008f05#diff-b5a9038b842c122f53873a82de638fbdcc0442783de3f120130129d903834614L175 doesn't actually deal with this happening again in the future, maybe we could do this task about trackers not crashing the app?

**Comment by arkon** [comment]
This is already addressed in preview/for the next stable release, including avoiding future crashes.
