### ISSUE TITLE
suddenly exits itself from the application

### ISSUE THREAD

**Issue by mozzaru** [tachiyomiorg/tachiyomi#9352]
### Steps to reproduce

open app

### Expected behavior

--------- beginning of system
--------- beginning of main
04-17 09:44:38.109 13723 14462 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:04.718 13723 14462 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:07.140 13723 17119 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:07.150 13723 17119 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:07.151 13723 17119 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:07.156 13723 17119 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:07.205 13723 17119 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:07.209 13723 17119 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:07.212 13723 17119 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:07.226 13723 13723 E ACRA    : ACRA caught a IllegalArgumentException for eu.kanade.tachiyomi
04-17 09:45:07.226 13723 13723 E ACRA    : java.lang.IllegalArgumentException: Key Screen#1:transition:lifecycle was used multiple times 
04-17 09:45:07.226 13723 13723 E ACRA    : 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:71)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:7)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:94)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:81)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:218)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:9)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:34)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:13)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1471)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:1270)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:977)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1458)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:938)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at android.os.Looper.loop(Looper.java:263)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8299)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
04-17 09:45:07.226 13723 13723 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@3671ecb, androidx.compose.ui.platform.MotionDurationScaleImpl@a4c26a8, StandaloneCoroutine{Cancelling}@423d5c1, AndroidUiDispatcher@2a90166]
04-17 09:45:07.402 17160 17160 E .tachiyomi:acr: Unknown bits set in runtime_flags: 0x40000000
04-17 09:45:07.406 17160 17160 E .tachiyomi:acr: Not starting debugger since process cannot load the jdwp agent.
04-17 09:45:07.413 17160 17160 E RefClass: java.lang.reflect.InvocationTargetException
04-17 09:45:07.459 17160 17160 E libc    : Access denied finding property "ro.odm.prev.product.name"
04-17 09:45:07.782 17160 17201 E SQLiteLog: (283) recovered 45 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
04-17 09:45:09.284 17234 17234 E anade.tachiyom: Unknown bits set in runtime_flags: 0x40000000
04-17 09:45:09.288 17234 17234 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
04-17 09:45:09.294 17234 17234 E RefClass: java.lang.reflect.InvocationTargetException
04-17 09:45:09.325 17234 17234 E libc    : Access denied finding property "ro.odm.prev.product.name"
04-17 09:45:09.625 17234 17281 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
04-17 09:45:09.628 17234 17286 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:09.988 17160 17160 E ANR_LOG : >>> msg's executing time is too long
04-17 09:45:09.989 17160 17160 E ANR_LOG : Blocked msg = { when=-2s426ms what=0 target=android.app.ActivityThread$H callback=eu.kanade.tachiyomi.AppModule$$ExternalSyntheticLambda0 } , cost  = 2208 ms
04-17 09:45:09.989 17160 17160 E ANR_LOG : >>>Current msg List is:
04-17 09:45:09.989 17160 17160 E ANR_LOG : Current msg <1> = { when=-2s209ms what=0 target=android.app.job.JobServiceEngine$JobHandler obj=android.app.job.JobParameters@2638166 }
04-17 09:45:09.989 17160 17160 E ANR_LOG : Current msg <2> = { when=-2s93ms what=0 target=android.app.ActivityThread$H callback=android.app.LoadedApk$ServiceDispatcher$RunConnection }
04-17 09:45:09.989 17160 17160 E ANR_LOG : Current msg <3> = { when=-1s846ms what=0 target=android.os.Handler callback=kotlinx.coroutines.internal.DispatchedContinuation }
04-17 09:45:09.989 17160 17160 E ANR_LOG : Current msg <4> = { when=-742ms what=0 target=android.os.Handler callback=kotlinx.coroutines.internal.DispatchedContinuation }
04-17 09:45:09.989 17160 17160 E ANR_LOG : Current msg <5> = { when=-1ms what=0 target=android.os.Handler callback=kotlinx.coroutines.internal.DispatchedContinuation }
04-17 09:45:09.989 17160 17160 E ANR_LOG : >>>CURRENT MSG DUMP OVER<<<
04-17 09:45:10.525 17234 17284 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:10.552 17234 17284 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:10.559 17234 17284 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:11.181 17234 17281 E SQLiteLog: (284) automatic index on C(manga_id)
04-17 09:45:11.182 17234 17281 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
04-17 09:45:11.728 17234 17365 E libEGL  : Invalid file path for libcolorx-loader.so
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 11 (SDK 30)
Android build ID: RMX2103_11_C.16
Device brand: realme
Device manufacturer: realme
Device name: RE50C1
Device model: RMX2103
Device product name: RMX2103T2

### Actual behavior

open app

### Crash logs

--------- beginning of system
--------- beginning of main
04-17 09:44:38.109 13723 14462 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:04.718 13723 14462 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:07.140 13723 17119 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:07.150 13723 17119 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:07.151 13723 17119 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:07.156 13723 17119 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:07.205 13723 17119 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:07.209 13723 17119 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:07.212 13723 17119 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:07.226 13723 13723 E ACRA    : ACRA caught a IllegalArgumentException for eu.kanade.tachiyomi
04-17 09:45:07.226 13723 13723 E ACRA    : java.lang.IllegalArgumentException: Key Screen#1:transition:lifecycle was used multiple times 
04-17 09:45:07.226 13723 13723 E ACRA    : 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:71)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:7)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:94)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:81)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:218)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:9)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:34)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:13)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1471)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:1270)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:977)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1458)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:938)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at android.os.Looper.loop(Looper.java:263)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8299)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
04-17 09:45:07.226 13723 13723 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
04-17 09:45:07.226 13723 13723 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@3671ecb, androidx.compose.ui.platform.MotionDurationScaleImpl@a4c26a8, StandaloneCoroutine{Cancelling}@423d5c1, AndroidUiDispatcher@2a90166]
04-17 09:45:07.402 17160 17160 E .tachiyomi:acr: Unknown bits set in runtime_flags: 0x40000000
04-17 09:45:07.406 17160 17160 E .tachiyomi:acr: Not starting debugger since process cannot load the jdwp agent.
04-17 09:45:07.413 17160 17160 E RefClass: java.lang.reflect.InvocationTargetException
04-17 09:45:07.459 17160 17160 E libc    : Access denied finding property "ro.odm.prev.product.name"
04-17 09:45:07.782 17160 17201 E SQLiteLog: (283) recovered 45 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
04-17 09:45:09.284 17234 17234 E anade.tachiyom: Unknown bits set in runtime_flags: 0x40000000
04-17 09:45:09.288 17234 17234 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
04-17 09:45:09.294 17234 17234 E RefClass: java.lang.reflect.InvocationTargetException
04-17 09:45:09.325 17234 17234 E libc    : Access denied finding property "ro.odm.prev.product.name"
04-17 09:45:09.625 17234 17281 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
04-17 09:45:09.628 17234 17286 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:09.988 17160 17160 E ANR_LOG : >>> msg's executing time is too long
04-17 09:45:09.989 17160 17160 E ANR_LOG : Blocked msg = { when=-2s426ms what=0 target=android.app.ActivityThread$H callback=eu.kanade.tachiyomi.AppModule$$ExternalSyntheticLambda0 } , cost  = 2208 ms
04-17 09:45:09.989 17160 17160 E ANR_LOG : >>>Current msg List is:
04-17 09:45:09.989 17160 17160 E ANR_LOG : Current msg <1> = { when=-2s209ms what=0 target=android.app.job.JobServiceEngine$JobHandler obj=android.app.job.JobParameters@2638166 }
04-17 09:45:09.989 17160 17160 E ANR_LOG : Current msg <2> = { when=-2s93ms what=0 target=android.app.ActivityThread$H callback=android.app.LoadedApk$ServiceDispatcher$RunConnection }
04-17 09:45:09.989 17160 17160 E ANR_LOG : Current msg <3> = { when=-1s846ms what=0 target=android.os.Handler callback=kotlinx.coroutines.internal.DispatchedContinuation }
04-17 09:45:09.989 17160 17160 E ANR_LOG : Current msg <4> = { when=-742ms what=0 target=android.os.Handler callback=kotlinx.coroutines.internal.DispatchedContinuation }
04-17 09:45:09.989 17160 17160 E ANR_LOG : Current msg <5> = { when=-1ms what=0 target=android.os.Handler callback=kotlinx.coroutines.internal.DispatchedContinuation }
04-17 09:45:09.989 17160 17160 E ANR_LOG : >>>CURRENT MSG DUMP OVER<<<
04-17 09:45:10.525 17234 17284 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:10.552 17234 17284 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:10.559 17234 17284 E libEGL  : Invalid file path for libcolorx-loader.so
04-17 09:45:11.181 17234 17281 E SQLiteLog: (284) automatic index on C(manga_id)
04-17 09:45:11.182 17234 17281 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
04-17 09:45:11.728 17234 17365 E libEGL  : Invalid file path for libcolorx-loader.so
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 11 (SDK 30)
Android build ID: RMX2103_11_C.16
Device brand: realme
Device manufacturer: realme
Device name: RE50C1
Device model: RMX2103
Device product name: RMX2103T2

### Tachiyomi version

Last

### Android version

Android 11

### Device

Realme 7i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by HHHhhh123456792** [comment]
Hi, I am facing the same issue with my Realme X2 Pro running Android 11. I noticed that most of the people who are getting the same error use mostly Oppo or Realme phones with Android 11. If you find a solution, please share it here.
