### ISSUE TITLE
Global Search Fails and App Crashes.

### ISSUE THREAD

**Issue by someonenameguy** [tachiyomiorg/tachiyomi#9434]
### Steps to reproduce

1. Run Global sreach with "I've Been Kicked Out of an S-Rank Guild. But Only I Can Communicate With Dragons. Before I Knew It, I Became the Greatest Dragon Knight"
2. wait for global search to finish.

### Expected behavior

Global Search finishes and nothing happens.

### Actual behavior

Global fails near end, then app crashes.

### Crash logs

```
--------- beginning of main
05-02 01:48:37.860  2910  2953 E SQLiteLog: (283) recovered 145 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
05-02 01:48:41.040  2910  3422 E SQLiteLog: (284) automatic index on C(manga_id)
05-02 01:48:41.040  2910  3422 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-02 01:50:02.253  4179  5166 E SQLiteLog: (284) automatic index on C(manga_id)
05-02 01:50:02.253  4179  5166 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-02 01:50:32.467  4179  5375 E chromium: [ERROR:simple_file_enumerator.cc(21)] opendir /data/user/0/eu.kanade.tachiyomi/app_webview/Default/DawnCache: No such file or directory (2)
05-02 01:50:32.467  4179  5375 E chromium: [ERROR:simple_index_file.cc(615)] Could not reconstruct index from disk
05-02 01:50:56.590  5549  6160 E SQLiteLog: (284) automatic index on C(manga_id)
05-02 01:50:56.590  5549  6160 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-02 01:51:21.313  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:24.259  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:24.372  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:25.108  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:25.198  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:25.211  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:25.390  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:27.197  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:27.339  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:27.416  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:31.693  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:31.744  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:32.151  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:35.479  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:35.597  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:35.753  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:37.238  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:37.470  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:37.623  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:38.281  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:38.423  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:40.165  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:41.818  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:43.181  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:44.621  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:44.761  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:45.314  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:45.544  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:45.569  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:45.677  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:45.702  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:45.897  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:47.150  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:50.224  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:56.045  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:51:56.084  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:52:05.271  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:52:09.056  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:52:09.809  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:52:19.390  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:52:52.783  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:52:52.974  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:53:03.114  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:53:03.334  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:53:23.978  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:53:24.166  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:53:28.671  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:53:28.788  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:53:29.580  5549  8225 E Surface : freeAllBuffers: 12 buffers were freed while being dequeued!
05-02 01:53:29.892  5549  8238 E Surface : freeAllBuffers: 11 buffers were freed while being dequeued!
05-02 01:53:30.016  5549  8247 E Surface : freeAllBuffers: 12 buffers were freed while being dequeued!
05-02 01:53:39.004  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:53:39.375  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:54:14.317  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -201
05-02 01:54:14.370  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -201
05-02 01:54:25.660  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:54:36.105  5549  6789 E chromium: [ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -101
05-02 01:55:01.736  5549  5549 E ACRA    : ACRA caught a Error for eu.kanade.tachiyomi
05-02 01:55:01.736  5549  5549 E ACRA    : java.lang.Error: Bad Request
05-02 01:55:01.736  5549  5549 E ACRA    : 	at eu.kanade.tachiyomi.extension.all.comico.Comico.getData(Comico.kt:179)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at eu.kanade.tachiyomi.extension.all.comico.Comico.popularMangaParse(Comico.kt:109)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at eu.kanade.tachiyomi.extension.all.comico.Comico.searchMangaParse(Comico.kt:135)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at eu.kanade.tachiyomi.source.online.HttpSource$fetchSearchManga$2.invoke(HttpSource.kt:2)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at eu.kanade.tachiyomi.source.online.HttpSource$fetchSearchManga$2.invoke(HttpSource.kt:1)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at eu.kanade.tachiyomi.source.online.HttpSource$$ExternalSyntheticLambda7.call(R8$$SyntheticClass:8)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:3)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.observers.Subscribers$5.onNext(Subscribers.java:3)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:13)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:30)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.Subscriber.setProducer(Subscriber.java:39)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:3)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.Subscriber.setProducer(Subscriber.java:22)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.Subscriber.setProducer(Subscriber.java:22)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$$ExternalSyntheticLambda0.call(R8$$SyntheticClass:24)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:2)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:1)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:3)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:1)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:4)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:1)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:4)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:1)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.Observable.subscribe(Observable.java:25)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at tachiyomi.core.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:28)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.source.globalsearch.SearchScreenModel$search$1$1$1$page$1.invokeSuspend(SearchScreenModel.kt:39)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
05-02 01:55:01.736  5549  5549 E ACRA    : 	at java.lang.Thread.run(Thread.java:1012)
05-02 01:55:01.736  5549  5549 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(Screen#1:eu.kanade.tachiyomi.ui.browse.source.globalsearch.GlobalSearchScreenModel:default:ScreenModelCoroutineScope), StandaloneCoroutine{Cancelling}@d2b51a3, Dispatchers.Main]
05-02 01:55:01.736  5549  5549 E ACRA    : Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: okhttp3.Response.class
05-02 01:55:01.736  5549  5549 E ACRA    : 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:20)
05-02 01:55:01.736  5549  5549 E ACRA    : 	... 27 more
05-02 01:55:04.950  8987  9034 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
05-02 01:55:08.192  8987  9756 E SQLiteLog: (284) automatic index on C(manga_id)
05-02 01:55:08.192  8987  9756 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.014.N986BXXU6HWCC
Device brand: samsung
Device manufacturer: samsung
Device name: c2s
Device model: SM-N986B
Device product name: c2sxxx
```

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Samsung Note 20 Ultra

### Other details

Screenshots of global Search errors before crash.
SSL error?
![Screenshot_20230502_023120_Tachiyomi](https://user-images.githubusercontent.com/54163580/235507864-dabd9ba1-d36f-4cc3-9535-c12ed112d849.png)
Parent job is canceling?
![Screenshot_20230502_015435_Tachiyomi](https://user-images.githubusercontent.com/54163580/235508113-45660607-659b-4a21-b303-45921315c12a.png)

All extension uptodate and All obsolete extensions uninstalled.
Webview uptodate.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Something seems to be wrong with the Comico extension

**Comment by someonenameguy** [comment]
Odd that it only effects this search term. I tried global searching other stuff they give no crashes...

**Comment by someonenameguy** [comment]
Seems to be the extension's issue. thanks for the help!
