### ISSUE TITLE
The application crashes when clicking on the extension's update notification

### ISSUE THREAD

**Issue by Boy656** [tachiyomiorg/tachiyomi#9451]
### Steps to reproduce

1-I received an update notification for one of the sources
2-Click on the notification to update
3-The app crashes and gives me a crash report

### Expected behavior

Click on the notification, then it takes me to the sources page and update the source to be updated

### Actual behavior

The app crashes and gives me an error report

### Crash logs
```
--------- beginning of main
05-04 19:18:06.466  7634  7670 E SQLiteLog: (283) recovered 41 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
05-04 19:18:06.607  7634  7634 E MsyncFactory: [static] ClassNotFoundException
05-04 19:18:06.607  7634  7634 E MsyncFactory: java.lang.ClassNotFoundException: com.mediatek.view.impl.MsyncFactoryImpl
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at java.lang.Class.classForName(Native Method)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at java.lang.Class.forName(Class.java:454)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at java.lang.Class.forName(Class.java:379)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at com.mediatek.view.MsyncFactory.<clinit>(MsyncFactory.java:14)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:761)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:857)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:393)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:134)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5011)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2324)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at android.os.Looper.loopOnce(Looper.java:210)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at android.os.Looper.loop(Looper.java:299)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at android.app.ActivityThread.main(ActivityThread.java:8273)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at java.lang.reflect.Method.invoke(Native Method)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
05-04 19:18:06.607  7634  7634 E MsyncFactory: Caused by: java.lang.ClassNotFoundException: com.mediatek.view.impl.MsyncFactoryImpl
05-04 19:18:06.607  7634  7634 E MsyncFactory: 	... 21 more
05-04 19:18:07.338  7634  7718 E SQLiteLog: (284) automatic index on C(manga_id)
05-04 19:18:07.338  7634  7718 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-04 19:18:07.673  7634  7674 E OpenGLRenderer: fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
05-04 19:18:07.673  7634  7674 E OpenGLRenderer: fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
05-04 19:18:14.656  7836  7836 E MsyncFactory: [static] ClassNotFoundException
05-04 19:18:14.656  7836  7836 E MsyncFactory: java.lang.ClassNotFoundException: com.mediatek.view.impl.MsyncFactoryImpl
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at java.lang.Class.classForName(Native Method)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at java.lang.Class.forName(Class.java:454)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at java.lang.Class.forName(Class.java:379)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at com.mediatek.view.MsyncFactory.<clinit>(MsyncFactory.java:14)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:761)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:857)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:393)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:134)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5011)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2324)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at android.os.Looper.loopOnce(Looper.java:210)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at android.os.Looper.loop(Looper.java:299)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at android.app.ActivityThread.main(ActivityThread.java:8273)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at java.lang.reflect.Method.invoke(Native Method)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
05-04 19:18:14.656  7836  7836 E MsyncFactory: Caused by: java.lang.ClassNotFoundException: com.mediatek.view.impl.MsyncFactoryImpl
05-04 19:18:14.656  7836  7836 E MsyncFactory: 	... 21 more
05-04 19:18:15.326  7836  7866 E OpenGLRenderer: fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
05-04 19:18:15.326  7836  7866 E OpenGLRenderer: fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: cannon
Device model: M2007J22C
Device product name: cannon
```

### Tachiyomi version

0.14.6

### Android version

android 12

### Device

redmi note 9 5g (cannon) (china version)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
I can't reproduce this, and the provided logs don't seem relevant. Please try to provide fresh crash logs if possible.

Potential ways of getting them, after reproducing the crash first:

- More → Settings → Advanced → Dump crash logs
- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA
