### ISSUE TITLE
Tachiyomi get force close

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#9570]
### Steps to reproduce

1. Open tachiyomi
2. Force close
3. Open again
4. Force close again
5. Open again
6. Force close again and automaticaly get crash logs
7. Crash logs can't be Generated (it says failed to create logs)

### Expected behavior

Tachiyomi can be opened

### Actual behavior

Force close 

### Crash logs

java.lang.Throwable: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 4874): , while compiling: PRAGMA journal_mode
	at io.requery.android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at io.requery.android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:22)
	at io.requery.android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:11)
	at io.requery.android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:6)
	at io.requery.android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:39)
	at io.requery.android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:11)
	at io.requery.android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:2)
	at io.requery.android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:7)
	at io.requery.android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:4)
	at io.requery.android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:2)
	at io.requery.android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:6)
	at io.requery.android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:22)
	at io.requery.android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:6)
	at io.requery.android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:94)
	at io.requery.android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:3)
	at io.requery.android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:1)
	at com.squareup.sqldelight.android.AndroidSqliteDriver$database$2.invoke(AndroidSqliteDriver.kt:11)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
	at com.squareup.sqldelight.android.AndroidSqliteDriver.access$getDatabase(AndroidSqliteDriver.kt:3)
	at com.squareup.sqldelight.android.AndroidSqliteDriver$executeQuery$1.invoke(AndroidSqliteDriver.kt:5)
	at com.squareup.sqldelight.android.AndroidSqliteDriver.execute(AndroidSqliteDriver.kt:3)
	at com.squareup.sqldelight.android.AndroidSqliteDriver.executeQuery(AndroidSqliteDriver.kt:13)
	at tachiyomi.data.data.UpdatesViewQueriesImpl$UpdatesQuery.execute(DatabaseImpl.kt:22)
	at com.squareup.sqldelight.Query.executeAsList(Query.kt:6)
	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4b61554, Dispatchers.Main.immediate]

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Realme 7i

### Other details

Its rare to get error like this, maybe just one in one week or more
![Screenshot_2023-06-03-18-00-22-89](https://github.com/tachiyomiorg/tachiyomi/assets/50316075/158ce934-14c9-4b29-8a8d-76d26750a047)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Do you have low storage space?

**Comment by TheKingTermux** [comment]
> Do you have low storage space?

Only ±1GB daily and i always clear all cache from app's at night

**Comment by arkon** [comment]
I suspect that it happens when it's too low then. Can't really do much if the system can't even get enough space to handle a database.
