### ISSUE TITLE
[crash][master] When Transitioning between Large Chapters in `Long Strip` Form

### ISSUE THREAD

**Issue by CalebMorris** [tachiyomiorg/tachiyomi#9632]
### Steps to reproduce

1. Navigate to `Browse` tab (note that I'm not viewing the manga in the Library tab; unsure if important)
2. Browse for target manga
3. Download several chapters (I had ch 12+ downloaded)
4. Open first downloaded chapter
5. Change view to `Long Strip`
6. Navigate to end of chapter
7. Scroll by flick to quickly jump down to next chapter and back up

Target Manga: `I'm Really Not the Demon's Lackey` (chapters are fairly large and slow to load for my phone)

### Expected behavior

Able to quickly navigate between chapter transitions, even if just showing loading indicators

### Actual behavior

App crashes

### Crash logs

--------- beginning of main
06-23 17:23:54.351 27991 27991 E GlobalExceptionHandler: java.lang.IllegalArgumentException: rectangle is outside the image
06-23 17:23:54.351 27991 27991 E GlobalExceptionHandler: 	at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:244)
06-23 17:23:54.351 27991 27991 E GlobalExceptionHandler: 	at tachiyomi.core.util.system.ImageUtil.splitStrip(ImageUtil.kt:303)
06-23 17:23:54.351 27991 27991 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonPageHolder$onStripSplit$newPages$1$1.invoke(WebtoonPageHolder.kt:245)
06-23 17:23:54.351 27991 27991 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonPageHolder$onStripSplit$newPages$1$1.invoke(WebtoonPageHolder.kt:245)
06-23 17:23:54.351 27991 27991 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonPageHolder$setImage$2.invokeSuspend(WebtoonPageHolder.kt:192)
06-23 17:23:54.351 27991 27991 E GlobalExceptionHandler: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-23 17:23:54.351 27991 27991 E GlobalExceptionHandler: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
06-23 17:23:54.351 27991 27991 E GlobalExceptionHandler: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
06-23 17:23:54.351 27991 27991 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
06-23 17:23:54.351 27991 27991 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
06-23 17:23:54.351 27991 27991 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
06-23 17:23:54.351 27991 27991 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
06-23 17:23:54.351 27991 27991 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
06-23 17:23:54.351 27991 27991 E GlobalExceptionHandler: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d8750b4, Dispatchers.Main]
App version: 0.14.6-5855 (dev, fcfa62f22, 103, 2023-06-24T00:07Z)
Android version: 13 (SDK 33)
Android build ID: 00WW_3_340_SP01
Device brand: Nokia
Device manufacturer: HMD Global
Device name: TTG_sprout
Device model: Nokia XR20
Device product name: TheThing_00WW

### Tachiyomi version

master branch (commit fcfa62f22)

### Android version

Android version: 13 (SDK 33)

### Device

Nokia XR20

### Other details

I can't reproduce this in the current `stable` version `0.14.6` for similar scrolling-view

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CalebMorris** [comment]
https://github.com/tachiyomiorg/tachiyomi/assets/347395/f3b6235f-4824-474d-82b1-cf1c53c9fba2

**Comment by CalebMorris** [comment]
https://github.com/tachiyomiorg/tachiyomi/assets/347395/51d4bc6a-4bc4-453c-90c0-be0fbc36cae3

**Comment by manavchaudhary1** [comment]
I don't know why this is happening with most of the users BUT
Here's a solution to your problem
OPEN SETTINGS in tachiyomi >READER> then in paged section you will find "spilt wide page" option TURN IT ON .
My problem solved with it hope it will solve yours too.
