### ISSUE TITLE
Crash when loading next unread chapter

### ISSUE THREAD

**Issue by Nikk452** [tachiyomiorg/tachiyomi#9704]
### Steps to reproduce

1. Start reading an unread chapter till the end
2. Keep going to the next chapter
3. Crash happens a second after loading pages for the loaded next chapter 

### Expected behavior

Should load the next chapter normally

### Actual behavior

App crashes a second after loading pages for next chapter
Not sure if it crashes for every entry
Doesn't crash if I try it with already read chapters

### Crash logs
```
--------- beginning of main
07-11 19:48:37.774  5638  5638 E DecorView[]: Destroying unexpected ActionMode instance of TYPE_FLOATING; com.android.internal.view.FloatingActionMode@5b6c9b1 was not the current floating action mode! Expected null
07-11 20:14:35.661 19763 19763 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
--------- beginning of system
07-11 20:14:35.929 19763 21118 E SQLiteLog: (283) recovered 290 frames from WAL file /data/user/0/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
07-11 20:14:36.604 19763 21263 E SQLiteLog: (284) automatic index on C(manga_id)
07-11 20:14:36.605 19763 21263 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-11 20:15:10.131 19763 21097 E DatabaseUtils: Writing exception to parcel
07-11 20:15:10.131 19763 21097 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.debug.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=20732, uid=1000 requires the provider be exported, or grantUriPermission()
07-11 20:15:10.131 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:841)
07-11 20:15:10.131 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:758)
07-11 20:15:10.131 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
07-11 20:15:10.131 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
07-11 20:15:10.131 19763 21097 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
07-11 20:15:10.131 19763 21097 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1190)
07-11 20:15:10.131 19763 21097 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1159)
07-11 20:15:10.246 19763 21097 E DatabaseUtils: Writing exception to parcel
07-11 20:15:10.246 19763 21097 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.debug.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=20732, uid=1000 requires the provider be exported, or grantUriPermission()
07-11 20:15:10.246 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:841)
07-11 20:15:10.246 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:758)
07-11 20:15:10.246 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
07-11 20:15:10.246 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
07-11 20:15:10.246 19763 21097 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
07-11 20:15:10.246 19763 21097 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1190)
07-11 20:15:10.246 19763 21097 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1159)
07-11 20:15:10.602 19763 21097 E DatabaseUtils: Writing exception to parcel
07-11 20:15:10.602 19763 21097 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.debug.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=20732, uid=1000 requires the provider be exported, or grantUriPermission()
07-11 20:15:10.602 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:841)
07-11 20:15:10.602 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:758)
07-11 20:15:10.602 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
07-11 20:15:10.602 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
07-11 20:15:10.602 19763 21097 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
07-11 20:15:10.602 19763 21097 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1190)
07-11 20:15:10.602 19763 21097 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1159)
07-11 20:15:24.153 19763 21097 E DatabaseUtils: Writing exception to parcel
07-11 20:15:24.153 19763 21097 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.debug.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=20732, uid=1000 requires the provider be exported, or grantUriPermission()
07-11 20:15:24.153 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:841)
07-11 20:15:24.153 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:758)
07-11 20:15:24.153 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
07-11 20:15:24.153 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
07-11 20:15:24.153 19763 21097 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
07-11 20:15:24.153 19763 21097 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1190)
07-11 20:15:24.153 19763 21097 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1159)
07-11 20:15:24.232 19763 21097 E DatabaseUtils: Writing exception to parcel
07-11 20:15:24.232 19763 21097 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.debug.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=20732, uid=1000 requires the provider be exported, or grantUriPermission()
07-11 20:15:24.232 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:841)
07-11 20:15:24.232 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:758)
07-11 20:15:24.232 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
07-11 20:15:24.232 19763 21097 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
07-11 20:15:24.232 19763 21097 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
07-11 20:15:24.232 19763 21097 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1190)
07-11 20:15:24.232 19763 21097 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1159)
07-11 20:15:24.355 19763 21095 E DatabaseUtils: Writing exception to parcel
07-11 20:15:24.355 19763 21095 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.debug.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=20732, uid=1000 requires the provider be exported, or grantUriPermission()
07-11 20:15:24.355 19763 21095 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:841)
07-11 20:15:24.355 19763 21095 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:758)
07-11 20:15:24.355 19763 21095 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
07-11 20:15:24.355 19763 21095 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
07-11 20:15:24.355 19763 21095 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
07-11 20:15:24.355 19763 21095 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1190)
07-11 20:15:24.355 19763 21095 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1159)
07-11 20:20:02.117 19763 22589 E CursorWindow: Failed to read row 2407, column 0 from a CursorWindow which has 2407 rows, 14 columns.
07-11 20:20:02.129 19763 19763 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi.debug
07-11 20:20:02.129 19763 19763 E ACRA    : java.lang.NullPointerException
07-11 20:20:02.129 19763 19763 E ACRA    : 	at tachiyomi.data.data.UpdatesViewQueriesImpl$getUpdatesByReadStatus$1.invoke(SourceFile:19)
07-11 20:20:02.129 19763 19763 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(SourceFile:18)
07-11 20:20:02.129 19763 19763 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(SourceFile:6)
07-11 20:20:02.129 19763 19763 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
07-11 20:20:02.129 19763 19763 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:112)
07-11 20:20:02.129 19763 19763 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4)
07-11 20:20:02.129 19763 19763 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
07-11 20:20:02.129 19763 19763 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
07-11 20:20:02.129 19763 19763 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
07-11 20:20:02.129 19763 19763 E ACRA    : 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8b5bf3c, Dispatchers.Main.immediate]
07-11 20:20:02.880 23700 23700 E yomi.debug:acr: Not starting debugger since process cannot load the jdwp agent.
07-11 20:20:03.079 23700 23737 E SQLiteLog: (283) recovered 54 frames from WAL file /data/user/0/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
07-11 20:20:12.156 22410 22410 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
07-11 20:20:13.045 22410 24999 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
07-11 20:20:37.659 22410 25404 E SQLiteLog: (284) automatic index on C(manga_id)
07-11 20:20:37.659 22410 25404 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.6-5901 (standard, 1e3d9a00f, 103, 2023-07-09T14:03Z)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.G985FXXS8DUE4
Device brand: samsung
Device manufacturer: samsung
Device name: y2s
Device model: SM-G985F
Device product name: y2sxx
```

### Tachiyomi version

Preview r5901

### Android version

Android 11

### Device

Samsung galaxy s20 plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Nikk452** [comment]
Edit: even if there is no next chapter it would crash too

**Comment by Nikk452** [comment]
Edit: when downloading chapters it would crash too when finished adownloading a chapter

**Comment by arkon** [comment]
Does this still happen on newer preview builds?
