### ISSUE TITLE
Chapter swipe related crash

### ISSUE THREAD

**Issue by AwkwardPeak7** [tachiyomiorg/tachiyomi#9819]
### Steps to reproduce

Have a long chapter list?
Quickly try to scroll down with vigorous motions 

### Expected behavior

Scroll downs

### Actual behavior

Trying to scroll down quickly apparently triggered the swipe gesture and crashed 

### Crash logs

[crash.txt](https://github.com/tachiyomiorg/tachiyomi/files/12271543/crash.txt)

### Tachiyomi version

r6993

### Android version

Android 13

### Device

Tecno spark 6 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
```
08-06 19:47:25.525 32195 32195 E ACRA    : kotlin.UninitializedPropertyAccessException: lateinit property canSwipeTowardsLeft has not been initialized
08-06 19:47:25.525 32195 32195 E ACRA    : 	at me.saket.swipe.SwipeableActionsState$draggableState$1.invoke(SourceFile:80)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at androidx.compose.foundation.gestures.DefaultDraggableState$dragScope$1.dragBy(SourceFile:19)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at androidx.compose.foundation.gestures.DraggableNode$onAttach$1$1.invokeSuspend(SourceFile:86)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at androidx.compose.foundation.gestures.DraggableNode$onAttach$1$1.invoke(SourceFile:13)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at androidx.compose.foundation.MutatorMutex$mutateWith$2.invokeSuspend(SourceFile:137)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at androidx.compose.foundation.MutatorMutex$mutateWith$2.invoke(SourceFile:13)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(SourceFile:8)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(SourceFile:10)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at androidx.compose.foundation.MutatorMutex.mutateWith(Unknown Source:11)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at androidx.compose.foundation.gestures.DefaultDraggableState$drag$2.invokeSuspend(SourceFile:41)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at androidx.compose.foundation.gestures.DefaultDraggableState$drag$2.invoke(SourceFile:13)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(SourceFile:8)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(SourceFile:10)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at androidx.compose.foundation.gestures.DefaultDraggableState.drag(SourceFile:7)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at androidx.compose.foundation.gestures.DraggableNode$onAttach$1.invokeSuspend(SourceFile:182)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:112)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(SourceFile:7)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(SourceFile:3)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:942)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:201)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at android.os.Looper.loop(Looper.java:288)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:7893)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-06 19:47:25.525 32195 32195 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
08-06 19:47:25.525 32195 32195 E ACRA    : 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@c762606, 
```

**Comment by sunwicked** [comment]
This looks like a library issue  
`kotlin.UninitializedPropertyAccessException: lateinit property canSwipeTowardsLeft has not been initialized`
https://github.com/search?q=repo%3Asaket%2Fswipe%20%20canSwipeTowardsLeft%20&type=code

Would be better to raise a ticket there as well  https://github.com/saket/swipe .
