### ISSUE TITLE
Random crash when spam installing extension 

### ISSUE THREAD

**Issue by AntsyLich** [tachiyomiorg/tachiyomi#9861]
### Steps to reproduce

1. Use sizuku or private installer.
2. Start clicking install on bunch of extension

### Expected behavior

Install as usual 

### Actual behavior

Random crash

### Crash logs

```
ACRA caught a SecurityException for eu.kanade.tachiyomi.debug
08-21 01:39:23.550 23659 24226 E ACRA    : java.lang.SecurityException: Unsupported path /storage/emulated/0/Android/data/eu.kanade.tachiyomi.debug/files/Download/tachiyomi-en.manhwafreak-v1.4.27.apk
08-21 01:39:23.550 23659 24226 E ACRA    : 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
08-21 01:39:23.550 23659 24226 E ACRA    : 	at android.os.Parcel.createException(Parcel.java:2410)
08-21 01:39:23.550 23659 24226 E ACRA    : 	at android.os.Parcel.readException(Parcel.java:2393)
08-21 01:39:23.550 23659 24226 E ACRA    : 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
08-21 01:39:23.550 23659 24226 E ACRA    : 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
08-21 01:39:23.550 23659 24226 E ACRA    : 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:557)
08-21 01:39:23.550 23659 24226 E ACRA    : 	at android.content.ContentResolver.insert(ContentResolver.java:2195)
08-21 01:39:23.550 23659 24226 E ACRA    : 	at android.content.ContentResolver.insert(ContentResolver.java:2157)
08-21 01:39:23.550 23659 24226 E ACRA    : 	at android.app.DownloadManager.enqueue(DownloadManager.java:1149)
08-21 01:39:23.550 23659 24226 E ACRA    : 	at eu.kanade.tachiyomi.extension.util.ExtensionInstaller.downloadAndInstall(SourceFile:75)
08-21 01:39:23.550 23659 24226 E ACRA    : 	at eu.kanade.tachiyomi.extension.ExtensionManager.installExtension(SourceFile:20)
08-21 01:39:23.550 23659 24226 E ACRA    : 	at eu.kanade.tachiyomi.ui.browse.extension.ExtensionsScreenModel$installExtension$1.invokeSuspend(SourceFile:33)
08-21 01:39:23.550 23659 24226 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
08-21 01:39:23.550 23659 24226 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:112)
08-21 01:39:23.550 23659 24226 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4)
08-21 01:39:23.550 23659 24226 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
08-21 01:39:23.550 23659 24226 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
08-21 01:39:23.550 23659 24226 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
08-21 01:39:23.550 23659 24226 E ACRA    : 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(eu.kanade.tachiyomi.ui.browse.BrowseTab:eu.kanade.tachiyomi.ui.browse.extension.ExtensionsScreenModel:default), StandaloneCoroutine{Cancelling}@43dd326, Dispatchers.IO]
```

### Tachiyomi version

r6011

### Android version

Android 12

### Device

realms C33

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Probably want to chunk/throttle.
