### ISSUE TITLE
Tachiyomi crashes when using page turn button on Boox Leaf 2

### ISSUE THREAD

**Issue by amarinne** [tachiyomiorg/tachiyomi#9891]
### Steps to reproduce

1. Use Tachiyomi on Boox Leaf 2 
2. Use page turn button to change pages

### Expected behavior

Change page like normal

### Actual behavior

Tachiyomi crashes

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/12461911/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Onyx Boox Leaf 2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
```
08-29 16:02:23.224  3919  3919 E ACRA    : ACRA caught a IndexOutOfBoundsException for eu.kanade.tachiyomi
08-29 16:02:23.224  3919  3919 E ACRA    : java.lang.IndexOutOfBoundsException: Index: 21, Size: 17
08-29 16:02:23.224  3919  3919 E ACRA    : 	at java.util.ArrayList.add(ArrayList.java:483)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewerAdapter.setChapters(PagerViewerAdapter.kt:179)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer.setChaptersInternal(PagerViewer.kt:35)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer.setChapters(PagerViewer.kt:10)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity.setChapters(ReaderActivity.kt:16)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity.access$setChapters(ReaderActivity.kt:1)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$onCreate$10.invokeSuspend(ReaderActivity.kt:38)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity$onCreate$10.invoke(ReaderActivity.kt:13)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:72)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:134)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:12)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:938)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at android.os.Looper.loop(Looper.java:223)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:7780)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-29 16:02:23.224  3919  3919 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
08-29 16:02:23.224  3919  3919 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@31b8d1, Dispatchers.Main.immediate]
08-29 16:02:23.650  4932  4932 E .tachiyomi:acr: Not starting debugger since process cannot load the jdwp agent.
08-29 16:02:24.345  4932  4974 E SQLiteLog: (283) recovered 19 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
08-29 16:02:28.384  5082  5082 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
08-29 16:02:29.008  5082  5118 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
08-29 16:02:31.692  5082  5221 E SQLiteLog: (284) automatic index on C(manga_id)
08-29 16:02:31.692  5082  5221 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 11 (SDK 30)
Android build ID: 2023-05-05_17-28_3.3.2_6745dfaa5
Device brand: Onyx
Device manufacturer: ONYX
Device name: Leaf2
Device model: Leaf2
Device product name: Leaf2
```
